### ISSUE TITLE
LDAP: NullPointerException in findAllGroupMembers

### ISSUE THREAD

**Issue by simar0at** [eXist-db/exist#2280] opened 2018-11-08 14:42 UTC
### What is the problem
LDAPRealm findAllGroupMembers is also called with built-in groups as parameter. Searching these in LDAP [results in a null return](https://github.com/eXist-db/exist/blob/develop/extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPRealm.java#L1240) which is not checked but [subseqently just used as an object](https://github.com/eXist-db/exist/blob/develop/extensions/security/ldap/src/org/exist/security/realm/ldap/LDAPRealm.java#L1242)

### What did you expect
Either that this function is only called on groups from the LDAP realm or that it handles null returns as not found gracefully.

### Describe how to reproduce or add a test

1. Configure LDAP
1. Let exist read the users from the DB
1. Try to change access rights using the GUI client
1. Edit Properties Error: Could not get dba group members: Failed to invoke method getGroupMembers in class org.exist.xmlrpc.RpcConnection: null

### Context information
Please always add the following information
- eXist 4.5.0-SNAPSHOT Git commit: f62496a5e Git branch: develop-4.x.x
- jdk1.8.0_192
- Windows 10
- 64 bit
- Compiled with IntelliJ IDEA from git source
- Enabled LDAP and configured it to read from an UCS Core Edition Samba AD replacement

**Comment by duncdrum** [comment] 2018-11-30 13:38
duplicate of #2281

**Comment by simar0at** [comment] 2018-11-30 13:50
If someone fixes this problem and #2281 then I'm fine with this being a duplicate. But that is a stretch of the word. These two problems only have in commen that they are within the same source file.

**Comment by duncdrum** [comment] 2018-11-30 13:59
From your description these seem the same problem to me, but if you think they're I'm happy to be shown otherwise.

**Closed** 2019-03-29 19:36 UTC
Labels: bug
