### ISSUE TITLE
Corrupt package repo XML file after repair action (3.6.0)

### ISSUE THREAD

**Issue by eriksiegel** [eXist-db/exist#1641] opened 2017-11-29 13:06 UTC
Seemingly innocent actions seems to cause the corruption of an XML file in package repo. After some research this is the minimum scenario that causes this:

- Did a fresh install of eXist 3.6.0
- Run the repo cleanup script from the eXist backup/restore docu page (not necessary but wanted to see what it did):

`import module namespace repair="http://exist-db.org/xquery/repo/repair" 
at "resource:org/exist/xquery/modules/expathrepo/repair.xql";
repair:clean-all(),
repair:repair()`

- This causes a non well-formed **(!)** XML file: `webapp\WEB-INF\data\expathrepo\shared-0.4.2E:\eXist\webapp\WEB-INF\data\expathrepo\shared-0.4.2\repo.xml`

- Its root element now reads: 
`<repo:meta xmlns="http://exist-db.org/xquery/repo" xmlns:repo="http://exist-db.org/xquery/repo" #unknown="http://exist-db.org/xquery/repo">`

And this causes many follow up problems in using or trying to change the package repo.

Context:
Please always add the following information
- eXist-db version: 3.6.0 
- Java version: 1.8.0_141
- Operating system: Windows server 2012 standard 64 bits

**Comment by adamretter** [comment] 2017-11-29 13:37
Thanks @eriksiegel this is a duplicate of https://github.com/eXist-db/exist/issues/1620

**Closed by adamretter** 2017-11-29 13:37 UTC
