### ISSUE TITLE
Parsing error XPST0003 when constructing attribute values

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#1988] opened 2018-07-01 21:53 UTC
### What is the problem

The following query raises an XPST0003 error in eXist, but does not in Saxon or BaseX:

```xquery
xquery version "3.1";

<x y="{'z'}"/>
```

The error:

> Cannot compile xquery: err:XPST0003 unexpected token: ' (while expecting closing tag for element constructor: x) [at line 3, column 8]

### What did you expect

I expected the query to return `<x y="z"/>`

### Describe how to reproduce or add a test

To trigger the error, use a direct constructor to create an attribute value with an enclosed expression beginning with a literal string - no matter the variant of single or double quotes used for the literal string:

```xquery
<x y="{"z"}"/>
<x y="{'z'}"/>
<x y='{"z"}'/>
<x y='{'z'}'/>
```

The error can be avoided if any other kind of expression appears (first) in the enclosed expression:

```xquery
<x y='{string-join(('z'), '')}'/>
<x y='{<z>z</z>}'/>
<x y='{1 || 'z'}'/>
<x>{ attribute y {'z'} }</x>
```

Comments don't work though:

```xquery
<x y='{(: darn :) 'z'}'/>
```

Again, Saxon and BaseX do not exhibit the error above.

### Context information

- eXist-db version: 5.0.0-RC1 develop ece9d6ded (also tested with 4.2.1)
- Java version: 1.8.0_172
- Operating system: macOS 10.13.5
- 32 or 64 bit: 64 bit
- How is eXist-db installed? build from source
- Any custom changes in e.g. conf.xml: none

**Comment by duncdrum** [comment] 2019-01-12 13:01
duplicate of #291

**Closed by duncdrum** 2019-01-12 13:01 UTC
Labels: bug, duplicate
