### ISSUE TITLE
Strange behaviour evaluating a boolean expression in RC2

### ISSUE THREAD

**Issue by dariok** [eXist-db/exist#1097] opened 2016-08-18 16:32 UTC
If have come across a situation where

    return $node/child1 and $node/child2

returns neither `true` nor `false` but nothing at all. **No exception is thrown**, either.

The code is available at https://gist.github.com/dariok/a4feb9ee14d58dff6aed0a2268cdf6d3
and you can see the result on a fairly fresh install of RC2 at http://dev2.hab.de:8080/exist/edoc/test/test3.xql

As you can see, both children can be accessed. If I check for the number of children, it works as well as can be seen in `dariok[@type='ondisk2']`.

**Comment by joewiz** [comment] 2016-08-18 17:00
@dariok Thanks for filing the issue. I wouldn't call this a conditional (if then else) issue, but rather a boolean issue (and). And your tests highlight the fact that the problem you're seeing only affects nodes stored in the database, not in-memory nodes. I have been unsuccessful at reproducing your problem. Let me provide a minimal test. Do you get the same result as me when running this test? If you do, we need to make the necessary adjustments to this test to trigger the problem:

1. Using a build of the current develop branch and current versions of eXide, dashboard, and shared-resources
2. Enter the following query into eXide and run "eval":

    ```xquery
xquery version "3.1";

declare namespace tei = "http://www.tei-c.org/ns/1.0";

let $in-memory-node := 
    <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="person">
        <forename/>
        <surname/>
    </persName>
let $store := xmldb:store('/db', 'test.xml', $in-memory-node)
let $on-disk-node := doc('/db/test.xml')/tei:persName
for $node in ($in-memory-node, $on-disk-node)
return
    ($node/tei:forename and $node/tei:surname)
```

3. Results: `(true(), true())`

Also, please let us know: Do you have any indexes defined on your `/db/edoc/ed000216` collection, particularly those involving the qnames in question (i.e., `persName`, `forename`, or `surname`)?

**Comment by dariok** [comment] 2016-08-18 17:12
@joewiz You're right, I've changed the title accordingly.

As I'll be out of office until Monday, I most likey won't be able to test this with a more recent build till then. I am currently using a fairly fresh install (done on Monday) of the RC2 download (3 August).

The only index on that collection (actually, it's parent collection) is on `div` which is not present in the file where the `person` records are stored.

Evaluating your code on my current installation returns `true()` and `true()`.

**Comment by joewiz** [comment] 2016-08-18 19:44
@dariok Okay, cool. Here's a further attempt to approximate your case: I've wrapped the `<persName>` in a `<div>` and set up an additional scenario where I have a lucene index on `<div>`.  Even with this addition, I'm getting the expected `true()` for all 3 cases:

```xquery
xquery version "3.1";

declare namespace tei = "http://www.tei-c.org/ns/1.0";

let $set-up-collections := 
    (
        xmldb:create-collection('/db', 'test'),
        xmldb:create-collection('/db/system/config/db', 'test')
    )
let $in-memory-node := 
    <div xmlns="http://www.tei-c.org/ns/1.0">
        <persName xml:id="person">
            <forename/>
            <surname/>
        </persName>
    </div>
let $store-unindexed-doc := xmldb:store('/db', 'test.xml', $in-memory-node)
let $store-indexed-doc := xmldb:store('/db/test', 'test.xml', $in-memory-node)
let $config := 
    <collection xmlns="http://exist-db.org/collection-config/1.0">
        <index xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tei="http://www.tei-c.org/ns/1.0">
            <fulltext default="none" attributes="false"/>
            <lucene>
                <analyzer class="org.apache.lucene.analysis.standard.StandardAnalyzer"/>
                <text qname="tei:div"/>
            </lucene>
        </index>
    </collection>
let $store-config := xmldb:store('/db/system/config/db/test', 'collection.xconf', $config)
let $reindex := xmldb:reindex('/db/test')
let $on-disk-unindexed-node := doc('/db/test.xml')/tei:div/tei:persName
let $on-disk-indexed-node := doc('/db/test/test.xml')/tei:div/tei:persName
for $node in ($in-memory-node/tei:persName, $on-disk-unindexed-node, $on-disk-indexed-node)
return
    ($node/tei:forename and $node/tei:surname)
```

**Comment by joewiz** [comment] 2016-08-18 19:57
@dariok I meant to add: if you're able to build on this to reproduce the case you're seeing, then we'll be all set on calling this a bug and attacking it as such.

**Comment by dariok** [comment] 2016-08-22 10:03
@joewiz I've just tested your code.
I had to remove line 22, `<fulltext default="none" attributes="false"/>` as I got a parser error that `fulltext` is invalid.
With this changed configuration, I get `true()` in all three cases.

**Comment by joewiz** [comment] 2016-08-22 13:48
@dariok Now the trick is to keep modifying the test to make it more and more like your original case, until produces the same failure.

**Comment by dariok** [comment] 2016-08-22 14:08
I have indeed been fiddling along building it up from your test and hopefully narrowed it further down:
https://gist.github.com/dariok/d5e0b972e59ed807e19db23c7c696fa5 gives three `true()` while 
https://gist.github.com/dariok/212da8c6e245aec773efa6ac9bb78da4 returns `true()` only twice.

**Comment by joewiz** [comment] 2016-08-22 17:43
The issue with test7.xql is in line 36:

```xquery
for $node in ($in-memory-node/tei:persName, $on-disk-unindexed-node, $on-disk-indexed-node)
```

The XPath for selecting the `persName` element should be:

```xquery
for $node in ($in-memory-node/tei:person/tei:persName, $on-disk-unindexed-node, $on-disk-indexed-node)
```

The revised gist is here: https://gist.github.com/joewiz/a652fe44045d2808d2ef26c1528b4079.

**Comment by dariok** [comment] 2016-08-23 09:53
Yes, indeed. Seems it weas too late for me already...
I have now built the example further up (see updated https://gist.github.com/dariok/212da8c6e245aec773efa6ac9bb78da4) and I still can't seem to reproduce it (I tried with and without `id()` and built it up step by step before adding the schema and `teiHeader`).
I'll keep trying.

**Comment by dariok** [comment] 2016-08-26 14:14
I've tried attacking this one from the other side as well by uploading a new `personenregister.xml` but the results of `test3.xql` as in my first post stay the same.

**Comment by joewiz** [comment] 2016-08-26 14:21
I just noticed something about your test3.xql: you use the `id` function on a collection rather than on a document: `collection('/db/edoc/ed000216')/id('reuchlin')/tei:persName`. Perhaps try this in your revised tests. You might also try adding some of the data from `/db/edoc/ed000216` into the `/db/test` collection to see if the presence of additional data has some effect.

**Comment by dariok** [comment] 2016-08-26 14:29
I have just changed `test3.xql` to also use `doc('/db/edoc/ed000216/register/personenregister.xml')//tei:person[@xml:id='accolti_pietro']/tei:persName` (I've updated the gist accordingly; note that I've selected a different entry).
The result is the same:

    <dariok type="ondisk"/>
    <dariok type="ondisk2">true</dariok>
    <dariok type="odn"/>
    <input type="odn2">
        <persName xmlns="http://www.tei-c.org/ns/1.0">
            <forename>Pietro</forename>
           <surname>Accolti</surname>
        </persName>
    </input>

**Comment by joewiz** [comment] 2016-08-26 14:53
Ok, perhaps try adding data then. Until we can reproduce your result, it's hard to help...

**Comment by dariok** [comment] 2016-08-26 15:03
I've just noticed something. See my updated gist:

    let $odn2 := doc('/db/edoc/ed000216/register/personenregister.xml')//tei:person[@xml:id='accolti_pietro']/tei:persName
    let $odn3 := doc('/db/edoc/ed000216/register/personenregister.xml')/id('accolti_pietro')/tei:persName

    for $node in ($in-memory-node, $in-mem-2, $on-disk-node, $odn2, $odn3)
    return
        $node/tei:forename and $node/tei:surname

returns `true true true true true`
while

    <dariok type="odn2">{$odn2/tei:surname and $odn2/tei:forename}</dariok>
    <dariok type="odn3">{$odn3/tei:surname and $odn3/tei:forename}</dariok>

returns

    <dariok type="ondisk"/>
    <dariok type="ondisk2">true</dariok>
    <dariok type="odn2"/>
    <dariok type="odn3"/>

----

I've then updated `test7.xql`. Adding about 10 more entries didn't change anything. Then I changed the bottom to

    let $odn2 := doc('/db/edoc/ed000216/register/personenregister.xml')//tei:person[@xml:id='accolti_pietro']/tei:persName
    let $odn3 := doc('/db/edoc/ed000216/register/personenregister.xml')/id('accolti_pietro')/tei:persName

    return <res><dariok type="odn2">{$odn2/tei:surname and $odn2/tei:forename}</dariok>
        <dariok type="odn3">{$odn3/tei:surname and $odn3/tei:forename}</dariok></res>

and was totally flabbergasted when that returned

    <res>
        <dariok type="odn2"/>
        <dariok type="odn3">true</dariok>
    </res>

----

I've now changed back and forth between these 2 scripts but the results stay the same (that is still true if I simply `return $odn[2|3]/tei:surname and $odn[2|3]/tei:forename`). They both reside in `/db/edoc/test/` yet produce different results.
I've also stored both scripts in `/db/test` where the results are the same.

**Comment by joewiz** [comment] 2016-08-26 15:21
Hmm, what kind of difference between `/db/edoc/test` and `/db/test` could account for the different results you're seeing? 

For anyone reading this, test7.xql can be found at https://gist.github.com/dariok/212da8c6e245aec773efa6ac9bb78da4.

I'd suggest adding a file, test7_results.xml, to your gist, with the results of your tests, to aid people in understanding the situation. As an example of this pattern, see https://gist.github.com/joewiz/ed624a43cb6f9e15cc44b6e30553ad5e, which contains both yaml-to-xml.xq and yaml-to-xml_results.xml.  The `_results` naming ensures that the results are sorted beneath the original file in the gist display.

**Comment by dariok** [comment] 2016-08-26 15:37
I'll update the gist. Just to clarify: Both test3.xql and test7.xql reside in `/db/edoc/test` yet give different results!

**Comment by joewiz** [comment] 2016-08-26 15:47
I see and understand you expect them to be similar, but test3.xql and test7.xql are quite different scripts:

test3.xql: https://gist.github.com/dariok/a4feb9ee14d58dff6aed0a2268cdf6d3
test7.xql: https://gist.github.com/dariok/212da8c6e245aec773efa6ac9bb78da4

Can you whittle down these differences to a key, single difference which results in the different results?

Sorry, I know I'm sounding insistent on simplifying and reducing differences, and keeping your presentation clear for those helping to troubleshoot, but this is the only way I know to move toward a solution.

**Comment by dariok** [comment] 2016-08-26 15:53
Perhaps I should refrase: I changed test7.xql from what is in the gist to what I posted in the long comment. In this case, in both files the nodes `$odn2` and `$odn3` were defined in the same way yet I got different results.
The reason was exactly as you said: Narrowing it down.
I'll do some more testing on this.

**Comment by dariok** [comment] 2016-08-26 16:02
Playing with test3.xql got interesting results. I've updated the gist to contain 2 different versions and their results. Note how removing `$in-memory-node` changes `<result type="odn3"/>` to `<result type="odn3">true</result>`.

**Comment by joewiz** [comment] 2016-08-26 16:10
This is very strange and very promising. Now, since no one else has your exact setup with `/db/edoc/ed000216`... can you create an example set that does not depend on your particular setup, in the style of test7.xql?

**Comment by dariok** [comment] 2016-08-26 16:13
Already on it. See my updated gist for test7.xql which I have ran from `/db/test` and the included result.

**Comment by joewiz** [comment] 2016-08-26 16:30
Okay, I've further reduced your test to the following:

```xquery
xquery version "3.1";

let $set-up-collection := xmldb:create-collection('/db', 'test')
let $in-memory-node := 
	<root>
		<foo/>
		<bar/>
	</root>
let $store-indexed-doc := xmldb:store('/db/test', 'test.xml', $in-memory-node)

let $x := doc('/db/test/test.xml')/root
let $y := doc('/db/test/test.xml')/root
return 
    <test>
        <result>{$x/foo and $x/bar}</result>
    	<result>{$y/foo and $y/bar}</result> 
    </test>
```

Results:

```xml
<test>
    <result/>
    <result>true</result>
</test>
```

**Comment by joewiz** [comment] 2016-08-26 16:34
To summarize: The result of a boolean operation on an in-memory nodes differs based on the order that the in-memory node is selected, with unexpected results as described in the test [above](https://github.com/eXist-db/exist/issues/1097#issuecomment-242783918).

**Comment by joewiz** [comment] 2016-08-26 16:40
A similar phenomenon can be observed in in-memory nodes:

```xquery
xquery version "3.1";

let $node := 
	<root>
		<foo/>
		<bar/>
	</root>
let $x := $node/blah
let $y := $node/blah
return 
    <test>
        <result>{$x/foo and $x/bar}</result>
    	<result>{$y/foo and $y/bar}</result> 
    </test>
```

Results:

```xml
<test>
    <result/>
    <result>false</result>
</test>
```

Obviously, this is an unexpected result. In testing, the phenomenon appears limited to boolean operations.

**Comment by joewiz** [comment] 2016-08-26 16:41
@dariok Can you reproduce my results?

**Comment by dariok** [comment] 2016-08-26 16:41
It seems that only the node selected last returns the right result: I tested with 3 nodes and only the last one returned `true()`.
Strangely enough, this does not happen when evaluating the same expression in a `for`.
It does not depend on the method of selecting the node.
Cf. my updated test7.xql.

**Comment by dariok** [comment] 2016-08-26 16:43
@joewiz Both your tests return the same results here.

**Comment by joewiz** [comment] 2016-08-26 16:43
Okay, we have a reproducible test confirming the bug. Core developers, please evaluate this as a bug report!

**Comment by joewiz** [comment] 2016-08-27 00:49
@shabanovd Thank you!

**Comment by adamretter** [comment] 2016-08-27 16:04
@joewiz @dariok Can we clean this ticket up so that it just contains the reproducible test case please?

**Comment by joewiz** [comment] 2016-08-27 19:07
Do you suggest we close this ticket and start a new one, or is there a different way besides @dariok and I each deleting our own comments?

**Comment by joewiz** [comment] 2016-08-27 19:18
I've written a new bug report in #1106. This ticket should be closed.

**Closed** 2016-08-28 08:30 UTC
Labels: bug
