### ISSUE TITLE
regression with closures in maps (since 3.4.0)

### ISSUE THREAD

**Issue by peterstadler** [eXist-db/exist#1550] opened 2017-09-20 08:21 UTC
### What is the problem
Starting with eXist version 3.4.0 inline functions within maps will not inherit variables declared outside its function body. The problem has been discussed on [eXist-open](https://sourceforge.net/p/exist/mailman/message/36045046/) and was confirmed by @joewiz by testing against Saxon and BaseX.

### What did you expect

I expected all three tests to pass without errors (as they do in eXist version 3.3.0).

### Describe how to reproduce or add a test

```xquery
xquery version "3.1";

module namespace ct="http://exist-db.org/xquery/closures/test";

declare variable $ct:model := function($param) {
    let $func := function() {
       $param
    }
    return
        map {
            'test1' : $func,
            'test2' : $func(),
            'test3' : function() {
                $param
            }
        }
};

declare %test:assertEquals('Hello World') function ct:test1-function-reference() as xs:string {
    try {
        $ct:model('Hello World')?test1()
    }
    catch * {$err:code || ' ' || $err:description}
};

declare %test:assertEquals('Hello World') function ct:test2-function-call() as xs:string {
    try {
        $ct:model('Hello World')?test2
    }
    catch * {$err:code || ' ' || $err:description}
};

declare %test:assertEquals('Hello World') function ct:test3-inline-function() as xs:string {
    try {
        $ct:model('Hello World')?test3()
    }
    catch * {$err:code || ' ' || $err:description}
};
```

### Context information
- eXist-db version 3.5.0-SNAPSHOT /  fdaabad
- Java 1.8.0_131 [Oracle Corporation]
- Operating system MacOs Capitan 64 bit
- vanilla build from develop branch

**Comment by joewiz** [comment] 2017-11-29 19:46
Reviewing the details in this issue again, I notice the URL to the HoF article that Peter referenced in his exist-open post unfortunately isn’t working: http://atomic.exist-db.org/blogs/eXist/HoF...

**Comment by peterstadler** [comment] 2017-11-30 10:40
The URL http://atomic.exist-db.org/blogs/eXist/HoF does work for me … maybe just a temporary server error?

**Comment by wolfgangmm** [comment] 2017-11-30 10:44
There were temporary hiccups with some pages on the server yesterday, which I fixed in the meantime.

It's best to point to http://exist-db.org/exist/apps/wiki/blogs/eXist/HoF though since http://atomic.exist-db.org is an old redirect.

**Comment by peterstadler** [comment] 2018-02-15 08:39
While I congratulate to the 4.0 release I tentatively want to remind you of this issue. It's something that keeps me from upgrading so I'm currently stuck with version 3.3.0.

Many thanks in advance!

**Comment by wolfgangmm** [comment] 2018-02-15 09:00
I had a look into this issue before 4.0 and I see where the problem is, but it's not straightforward to fix without potentially causing other regressions, so I did not want to risk it for the release.

**Comment by peterstadler** [comment] 2018-02-16 13:42
Thanks for the reply! I was just trying to make sure it wont be forgotten ;)

**Comment by peterstadler** [comment] 2018-07-09 15:39
Help! This is really an issue for me that prevents me from upgrading to a recent eXist version. Is a fix anywhere on the roadmap or do I have to refactor my code?

**Comment by wolfgangmm** [comment] 2018-07-09 15:53
Assigning high prio for myself.

**Comment by peterstadler** [comment] 2018-11-22 10:14
Sorry for bothering, but is there any chance this will be tackled in the near future?

**Comment by duncdrum** [comment] 2018-11-22 10:41
not directly related,  but because namespace prefixes can appear in maps,  the preferred and specs compliant map syntax is 
```XQuery
return
        map {
            'test1': $func,
            'test2': $func(),
            'test3': function() {
                $param
            }
        }

```

only one ws after `:` in `{ key: value }`

**Comment by adamretter** [comment] 2018-11-22 14:31
@peterstadler I think you will have to ask @wolfgangmm

**Comment by peterstadler** [comment] 2019-01-15 10:20
@duncdrum  shall I create a PR for the tests?

**Closed** 2019-03-26 04:32 UTC
Labels: bug, high prio, regression
