### ISSUE TITLE
[BUG] Quest should raise an error but doesn't

### ISSUE THREAD

**Issue by alanpaxton** [eXist-db/exist#4383] opened 2022-05-09 13:23 UTC
**Describe the bug**
Error checking not showing a problem

**Expected behavior**
This query should raise an error, but it does not at the moment

**To Reproduce**

```Xquery
xquery version "3.1";

declare function local:foo(
) as element(bar)
{
    <not-bar>test</not-bar>
};

local:foo()
```

**Context
 - OS: macOS 11.6.5
 - eXist-db version: 6.10.0-SNAPSHOT
 - Java Version: openjdk 11.0.8 2020-07-14 LTS

**Additional context**
- How is eXist-db installed? built from source. ./exist-distribution/target/exist-distribution-6.1.0-SNAPSHOT-dir/bin/launcher.sh
This error was first reported as a comment on https://github.com/eXist-db/exist/issues/1917 - we're turning it into a separate issue, it's not part of the core of that.

**Comment by joewiz** [comment] 2022-05-09 13:54
@alanpaxton This appears to be a dupe of #3780.

**Comment by alanpaxton** [comment] 2022-05-10 08:58
Closed as duplicate.

**Closed** 2022-05-10 08:58 UTC
