### ISSUE TITLE
Different behavior for global variables in static/dynamic module load

### ISSUE THREAD

**Issue by xatapult** [eXist-db/exist#4137] opened 2021-12-20 10:22 UTC
**Describe the bug**

We're *dynamically* importing an XQuery module using `load-xquery-module()`. This module has a global variable that computes its value using a `=>` operator. When doing this dynamic import, a null pointer error occurs, nothing turns up in the exist.log.

The (test) expression that already causes the bug is the very simple: `'xxx' => upper-case()`, but is observed at every usage of `=>` for computing a global variable.

Rewriting the test expression to `upper-case('xxx')` makes the bug disappear.

The following observations:

* Statically importing the same module (using an `import` clause in the prolog) works fine
* I've been struggling with this problem for hours now, trying to pinpoint it but it is rather evasive. I had for instance to change a FLWOR `group by` clause (in computing a global variable)  into something else to make another dynamic input null pointer exception disappear. I could unfortunately not create a decent reproducible test case for it, because it was all very deep into complicated code.

So my guess is that something weird is going on at dynamically loading XQuery modules and specifically the computation of their global variables. It seems like its doing something different than when its statically importing modules. 

**Expected behavior**
Static and dynamic importing XQuery modules should work the same. When something's wrong at least a decent error should be thrown and not a null pointer exception. `=>` should simply work.

**To Reproduce**
[test-function-lookup.zip](https://github.com/eXist-db/exist/files/7744482/test-function-lookup.zip)

* Import the contents of this zip file somewhere in eXist
* Change the value of the XQuery module URI in line 48 of `test-function-lookup.xql` into the correct path (it's now set to  `/db/TEST/test-function-lookup/test.xqm`)
* Execute `test-function-lookup.xql`. On my machine this causes a null pointer exception

**Context (please always complete the following information):**
 - OS: Windows 10
 - eXist-db version: 5.3.0
 - Java Version 
 ```
openjdk version "1.8.0_282"
OpenJDK Runtime Environment Corretto-8.282.08.1 (build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM Corretto-8.282.08.1 (build 25.282-b08, mixed mode)
```

**Additional context**
- How is eXist-db installed? JAR
- Started using launcher.bat
- Any custom changes in e.g. `conf.xml`? Many but nothing seems relevant

**Comment by adamretter** [comment] 2021-12-20 10:44
@xatapult I fixed an NPE with a variable declaration in modules recently. I wonder if this is related... could you post the stacktrace for the NPE please?

**Comment by xatapult** [comment] 2021-12-20 11:55
@adamretter With pleasure, but there is no stack trace in the error message nor in the exist.log. The only visible thing in the exist.og is a message: `2021-12-20 12:53:20,735 [qtp2047155002-155] WARN  (TransactionManager.java [close]:421) - Transaction was not committed or aborted, auto aborting! `

Don't know whether that helps. If not, how can I obtain one?

**Comment by adamretter** [comment] 2021-12-20 12:49
Where do you see the NPE? Is it in the browser?

**Comment by xatapult** [comment] 2021-12-20 12:52
I run the accompanying code from within oXygen.

**Comment by joewiz** [comment] 2021-12-20 15:05
@xatapult Could you paste in the full error that you get in oXygen?

**Comment by adamretter** [comment] 2021-12-20 15:25
@xatapult Thanks very much for reporting :-)

I was unable to reproduce your NPE on eXist-db 5.4.0-SNAPSHOT. I am fairly certain this was likely resolved by my recent fix - https://github.com/eXist-db/exist/pull/4120

<img width="952" alt="Screenshot 2021-12-20 at 16 22 50" src="https://user-images.githubusercontent.com/1264057/146791221-f8ae43d9-ce15-41ac-a0d7-0e1dfe5e267d.png">

**Closed by adamretter** 2021-12-20 15:25 UTC
