### ISSUE TITLE
login problems in 3.2 (and 3.0 and 3.1)

### ISSUE THREAD

**Issue by eduarddrenth** [eXist-db/exist#1452] opened 2017-06-07 07:36 UTC
I experience a login in 3.2 (and 3.0 and 3.1) when using the dashboard:

1. open dashboard
2. login
3. click package manager => nothing happens
4. login AND check remember
5. click package manager => opens

Same behaviour when opening other "apps" from the dashboard.

**Comment by duncdrum** [comment] 2017-06-07 07:50
Which OS, and java is what do the logs say when you `` click package manager => nothing happens`` ? Could it be one of these two issues: https://github.com/eXist-db/exist/issues/1432 or https://github.com/eXist-db/dashboard/issues/44

**Comment by eduarddrenth** [comment] 2017-06-07 08:38
ubuntu 1604, java jdk1.8.0_121, firefox 53.0.3
nothing in the logs
it is not #1432 

I don't think its #44 either becasue I see nothing in the logs. I'll do some more testing, see what the browser does etc.

**Comment by eduarddrenth** [comment] 2017-06-07 09:16
Just before filing this issue I tested if it still existed, it did.

After you asked your OS questions I tested again, to produce some logging. Since then I cannot reproduce the issue anymore. Did not change anything though, not in exist, not in firefox.

Maybe starting client.sh, which I did in the mean time (and never before), triggered something,

I do see a lot of these lines in the log.

DefaultQuartzScheduler_Worker-1] ERROR (FileUtils.java [measureFileStore]:193) - java.nio.file.NoSuchFileException: /home/eduard/eXist-db3.2/webapp/WEB-INF/data/dbx_dir.lck

Perhaps close this issue since it cannot be reproduced. Though it woories me a bit to not know what was going on.

**Comment by duncdrum** [comment] 2017-06-07 09:25
sounds like exist expected a lock file. Could it be that another instance hadn't shut down completely, was doing a backup, or restoring when you experienced the issue?  I d leave it open for a day or two to give the pros a chance of chiming in. If the problem doesn't come back go ahead and close.

**Comment by eduarddrenth** [comment] 2017-06-07 10:02
no other instance, backup or restore. I'll keep it open for a
while...Thanks sofar

**Comment by eduarddrenth** [comment] 2017-06-17 06:33
It could be related to "remember me". On the mailing list I posted a problem: seeing "Permission denied, user 'guest' must be a DBA to reindex the database" in the log while being logged in as admin. That issue dissappears when not using "remember me".
Now I think this issue may have been caused by using "remember me" in the past on an installation (which I removed, so I cannot test that).
Perhaps file a separate issue to have a good look at persistent login? Also because in the mailing archives I read more about problems with it. Perhaps even drop the persistent login functionality?

**Comment by joewiz** [comment] 2018-06-09 18:16
Closed by https://github.com/eXist-db/dashboard/pull/64. Please reopen or file a new issue if you're still experiencing a problem.

**Comment by eduarddrenth** [comment] 2019-02-26 11:22
loging in still problematic (I think when using firefox).

starting package manager only succeeds after logging in in monex

**Comment by joewiz** [comment] 2019-02-26 15:39
@eduarddrenth I see this too on the old Dashboard, but there is no more development on that version. Can you migrate to the new Dashboard? It's currently housed at https://github.com/eXist-db/existdb-dashboard and available via the Package Manager. Highly recommended.

**Comment by eduarddrenth** [comment] 2019-02-26 18:21
looking good....but in this new app I miss the package manager and more (8 versus 15 apps in the old dashboard)

**Comment by eduarddrenth** [comment] 2019-02-26 18:24
looking good....but in this new app I miss the package manager and more (8 versus 15 apps in the old dashboard)

But wait...after clicking login I see more....I'll have a look

**Comment by eduarddrenth** [comment] 2019-02-28 12:04
missing from new dashboard: Collections

**Comment by joewiz** [comment] 2019-02-28 15:38
Missing by design. Please use eXide's DB Manager via File > Manage.

**Closed by joewiz** 2019-02-28 15:38 UTC
Labels: triage

**Comment by eduarddrenth** [comment] 2019-02-28 15:47
fair enough
