### ISSUE TITLE
[BUG] WebDAV error  409 "Conflict" when updating a file - which is the same like deleting these!

### ISSUE THREAD

**Issue by Spaxx71** [eXist-db/exist#4213] opened 2022-01-28 13:02 UTC
After updating from eXist-db 5.3.1 to 6.0.0 the webdav access often fails when updating an xml, xsl or xconf file.
Before updating eXist-db to Version 6 all worked fine, as long as the following two Java options are given:
`-Dorg.exist.webdav.PROPFIND_METHOD_XML_SIZE=EXACT -Dorg.exist.webdav.GET_METHOD_XML_SIZE=EXACT`

The exist.logs looks like this:

```
2022-01-28 12:18:03,028 [qtp1993812827-32] INFO  (HttpManager.java [process]:213) - PUT :: http://exist-proxy/exist/webdav/db/apps/mywebsite/general/templates/generate-html.xsl - http://exist-proxy/exist/webdav/db/apps/mywebsite/general/templates/generate-html.xsl 
2022-01-28 12:18:03,031 [qtp1993812827-32] INFO  (MiltonResource.java [authorise]:356) - PUT /db/apps/mywebsite/general/templates (write=true) 
2022-01-28 12:18:03,036 [qtp1993812827-32] ERROR (NativeBroker.java [dropDomNodes]:2862) - Caught NPE in DOMTransaction to actually be able to remove the document. 
2022-01-28 12:18:03,036 [qtp1993812827-32] WARN  (TransactionManager.java [close]:421) - Transaction was not committed or aborted, auto aborting! 
2022-01-28 12:18:03,037 [qtp1993812827-32] ERROR (ExistCollection.java [createFile]:327) - org.xml.sax.SAXException: fatal error at (-1,-1) : Premature end of file.
org.xml.sax.SAXParseException; Premature end of file. 
2022-01-28 12:18:03,037 [qtp1993812827-32] WARN  (StandardFilter.java [process]:62) - conflictException: Conflict exception: templates 
2022-01-28 12:18:04,992 [qtp1993812827-49] INFO  (HttpManager.java [process]:213) - PROPFIND :: http://exist-proxy/exist/webdav/db/apps/mywebsite/general/templates/ - http://exist-proxy/exist/webdav/db/apps/mywebsite/general/templates/ 
2022-01-28 12:18:04,993 [qtp1993812827-49] INFO  (MiltonResource.java [authorise]:356) - PROPFIND /db/apps/mywebsite/general/templates (write=false) 
2022-01-28 12:18:04,994 [qtp1993812827-49] INFO  (MiltonResource.java [authorise]:356) - PROPFIND /db/apps/mywebsite/general/templates (write=false)
```

The NGINX (used as reverse proxy) logfile looks like this:

```
93.241.78.156 - admin [28/Jan/2022:12:16:53 +0000] "PROPFIND /exist-proxy/webdav/db/apps/mywebsite/general/templates/ HTTP/1.1" 207 12901 "-" "WinSCP/5.19.5 neon/0.31.2"
93.241.78.156 - admin [28/Jan/2022:12:17:59 +0000] "PROPFIND /exist-proxy/webdav/db/apps/mywebsite/general/templates/generate-html.xsl HTTP/1.1" 207 1128 "-" "WinSCP/5.19.5 neon/0.31.2"
93.241.78.156 - admin [28/Jan/2022:12:18:03 +0000] "PUT /exist-proxy/webdav/db/apps/mywebsite/general/templates/generate-html.xsl HTTP/1.1" 409 5 "-" "WinSCP/5.19.5 neon/0.31.2"
93.241.78.156 - admin [28/Jan/2022:12:18:05 +0000] "PROPFIND /exist-proxy/webdav/db/apps/mywebsite/general/templates/ HTTP/1.1" 207 12901 "-" "WinSCP/5.19.5 neon/0.31.2"
```

**Describe the bug**

When using a webdav access as remote access to exist all works fine. But when updating or copying an xml, xls or xconf file, an http error "409 Conflict" is been given back. But the file has been updated to be empty (0 bytes). 
Even when accessing eXist as admin. 

**Expected behavior**

When updating or copying an xml based file, it should be stored fine. As long as the acces is granted. 

**To Reproduce**

a) take an webdav tool (like WinSCP, Cyberduck or FileZilla
b) connect to exist by using the webdav URL  http://localhost:8080/exist/webdav/db/apps/ as admin
c) transfer a text file and double check that its file size is not 0 after it has been stored
d) transfer a xml file 
--> you will expect an http response code "409 Conflict" and the file size will be update to 0 bytes

**Screenshots**
no screenshot given

**Context (please always complete the following information):**
 - OS: Debian 11 (bullseye) 
 - eXist-db version: 6.0.0
 - Java Version: openJDK 17.0.2

**Additional context**
To start exist as a service, systemctl is been used.

/etc/system.d/system/exist-db.service looks like this:

```
[Unit]
Description=eXist-db Server
Documentation=
After=syslog.target

[Service]
Environment="JAVA_OPTS=-Dorg.exist.db-connection.cacheSize=512M -Dorg.exist.webdav.PROPFIND_METHOD_XML_SIZE=EXACT -Dorg.exist.webdav.GET_METHOD_XML_SIZE=EXACT -Xms1536m -Xmx1536m"
Type=simple
Restart=always
RestartSec=1
User=existdb
Group=www-data
ExecStart=/etc/exist-db/bin/startup.sh
ExecStop=/etc/exist-db/bin/shutdown.sh

[Install]
WantedBy=multi-user.target
```

**Comment by line-o** [comment] 2022-01-28 14:19
@Spaxx71 Thank you for reporting this. Would you be able to test if 5.4.0 shows the same behaviour?

**Comment by Spaxx71** [comment] 2022-01-28 19:26
Version 5.4.0 and version 6.0.0 do have this problem.
Version 5.3.1 is working fine.
All three versions have been testet by a fresh installment, with the same dataset (restored the same way by using bin/backup.sh) and at the same environment (to enshure no difference of Linux, Java, Proxy, Firewall).

**Comment by Spaxx71** [comment] 2022-01-28 19:29
For two of our environments, the WebDAV is the most important way for data base access. 
Therefore I would suggest to handle this as a critical bug, as all uploads and edits will delete files.

**Comment by adamretter** [comment] 2022-01-30 10:25
@dizzzz It looks like only `propfindSizeMethod` is used, I can't find anywhere where `getSizeMethod` is used. Any thoughts?

**Comment by dizzzz** [comment] 2022-01-30 11:55
I will have a look...

**Comment by adamretter** [comment] 2022-01-31 19:36
@Spaxx71 can you try and reproduce this on Java 8?

**Comment by adamretter** [comment] 2022-02-07 23:15
@Spaxx71 Thanks for your issue report, I have now written tests that can reproduce your issues here - https://github.com/evolvedbinary/exist/tree/hotfix/webdav/extensions/webdav/src/test/java/org/exist/webdav

I hope to create a fix for this in the next few days.

**Comment by Spaxx71** [comment] 2022-02-09 07:03
> @Spaxx71 can you try and reproduce this on Java 8 please? Officially we don't support Java 17 yet.

Took some time, as even for Debian Java 8 is quite outdated... The result is the same. Java version does not make a difference.

**Closed** 2022-02-09 21:23 UTC
Labels: bug, regression, high prio
