### ISSUE TITLE
eXist-db 4.0 User Manager broken for contextPath /

### ISSUE THREAD

**Issue by ahenket** [eXist-db/exist#1735] opened 2018-02-16 10:52 UTC
macOS 10.13.4, eXist-db 4.0.0 (dmg version official release)

I’ve just downloaded and installed eXist-db. As per usual we configure the contextPath in jetty.xml as / instead of the default /exist. Apparently that trips up the user manager in the new 4.0 version. 

Clicking the User Manager from the Dashboard leads to a page with a reported HTTP 404. 

Looking in the browser inspector, it turns out many paths are hard coded to go to /exist/apps instead of /apps.

![schermafbeelding 2018-02-15 om 11 17 17](https://user-images.githubusercontent.com/5390573/36304421-de1d037c-130f-11e8-80a9-05b4e210bf1a.png)

**Comment by adamretter** [comment] 2018-02-16 12:27
I believe this is a duplicate of - https://github.com/eXist-db/usermanager/issues/12
So I will close this and suggest moving the discussion there.

**Closed by adamretter** 2018-02-16 12:27 UTC
