### ISSUE TITLE
compression:gzip() malfunction

### ISSUE THREAD

**Issue by peterstadler** [eXist-db/exist#39] opened 2013-09-11 15:08 UTC
see http://exist.2174344.n4.nabble.com/compression-gzip-tp4661212.html

**Comment by adamretter** [comment] 2015-04-12 09:56
This is related to https://github.com/eXist-db/exist/issues/492

**Comment by zwobit** [comment] 2015-09-08 08:36
This should be fixed with the 5ef94c1f484108077d869d8882533b358dc9c4f5. @peterstadler could you please test?

**Comment by peterstadler** [comment] 2015-09-09 10:13
Sorry to say, but I'm still having difficulties.

My compression function is:
```XQuery
declare function local:compressXML($xml as element(), $fileName as xs:string, $compression as xs:string) as xs:base64Binary? {
    if($compression eq 'zip') then compression:zip(<entry name="{$fileName}" type="xml" method="deflate">{$xml}</entry>, false())
    else if($compression eq 'gz') then (
        let $serializationParameters := ('method=xml', 'media-type=application/xml', 'indent=no', 'omit-xml-declaration=no', 'encoding=utf-8')
        return compression:gzip(util:string-to-binary(util:serialize($xml, $serializationParameters)))
    )
    else ()
};
```

Though gz didn't work in the past, zip did. Now both of them fail. Trying a simple round trip

```XQuery
let $xml := <a>foo bar</a>
let $archive := local:compressXML($xml, 'someName', 'gz')
return
    util:base64-decode(compression:ungzip($archive))
```

fails with error
```
err:XPTY0004 checking function parameter 1 in call util:base64-decode(untyped-value-check[xs:string, compression:ungzip(untyped-value-check[xs:base64Binary, $archive])]): Unexpected end of ZLIB input stream [at line 28, column 24]
```

My system:
* eXist Version : 3.0.RC1
* eXist Build : 20150908
* Git commmit : develop-5ef94c1
* Operating System : Mac OS X 10.10.5 x86_64

**Comment by dizzzz** [comment] 2015-09-11 12:29
I can confirm... a recent change did break the compression:zip() function ; I think a last part of the file is missing.

**Comment by adamretter** [comment] 2015-09-11 12:34
@dizzzz Tobi (@zwobit) and I discussed this yesterday. The code for the zip stuff before worked by fluke rather than intention, cleaning up the code introduced the issue for sure. Tobi and I have a fix we discussed, however Tobi is looking at how to actually improve the code as it still misuses the compression stream.

**Comment by dizzzz** [comment] 2015-09-11 12:42
Ah ok; it probably explains why I had a hard time trying to fix the `repair:repo()` code where the same zip functions are used. [I thought I found the issue]

**Comment by adamretter** [comment] 2015-10-18 13:43
@peterstadler @dizzzz Can you tell me if this works for you in this branch - https://github.com/adamretter/exist/tree/feature/gzipfunction

**Comment by peterstadler** [comment] 2015-10-19 19:42
Hi @adamretter, just tried your branch and indeed it fixes the compression:zip() function for me. Yet, my gzip-roundtrip-example above still fails with (new error message): 

> err:XPTY0004 checking function parameter 1 in call util:base64-decode(untyped-value-check[xs:string, compression:ungzip(untyped-value-check[xs:base64Binary, $archive])]): Not in GZIP format [at line 21, column 24]

**Comment by dizzzz** [comment] 2015-10-19 20:09
makes sense, I think the following lines need to be swapped:

```java
          gzos.flush();
          gzos.finish();
```

**Comment by adamretter** [comment] 2015-10-19 20:17
@peterstadler Okay so this is weird, but I think we have a double encoding issue happening somewhere. The following code works for me:

```
util:base64-decode(
	util:binary-to-string(
		compression:ungzip(
			compression:gzip(
				util:string-to-binary(fn:serialize($xml,
					<output:serialization-parameters>
						<output:method value="xml"/>
						<output:media-type value="application/xml"/>
						<output:indent value="no"/>
						<output:omit-xml-declaration value="no"/>
						<output:encoding value="UTF-8"/>
					</output:serialization-parameters>
				))
			)
		)
	)
)
```

Needing both the nested `util:base64-decode(util:binary-to-string(` is weird no? I expected to only need the `util:binary-to-string`

**Comment by adamretter** [comment] 2015-10-19 20:23
For comparison, this one works just fine:

```
let $xml := <a>foo bar</a>
return
	compression:unzip(
		compression:zip(<entry name="out.xml" type="xml" method="deflate">{$xml}</entry>, false()),
		function($path, $data-type, $param) { true() },
		(),
		function($path, $data-type, $param) { "/db/out.xml" },
		()
	)
```

**Comment by peterstadler** [comment] 2015-10-19 21:32
sorry, it's late … my above error message "Not in GZIP format" was due to my fault trying to ungzip a zipped archive, argh.

But the double encoding issue is still there. As I said, I'm using the gzip function for creating a sitemap and I can't convince Mr. Google to base64-decode the string ;)

**Comment by adamretter** [comment] 2015-10-27 12:12
It turns out that `compression:gzip` was compressing the Base64 encoded representation of the binary value and not the raw binary value. I have fixed this in https://github.com/eXist-db/exist/pull/822

**Closed** 2015-10-27 12:26 UTC
Labels: bug
