### ISSUE TITLE
cannot run exist-db when installed as war on payara

### ISSUE THREAD

**Issue by eduarddrenth** [eXist-db/exist#2518] opened 2019-02-26 10:58 UTC
### What is the problem
after installing exist war 4.6 or higher on payara browse to the app I see:

![image](https://user-images.githubusercontent.com/10200360/53407468-8fc1fa00-39bc-11e9-949f-2296c6ce7107.png)

Clicking the link gives me:

![image](https://user-images.githubusercontent.com/10200360/53407815-563dbe80-39bd-11e9-975e-fc16dfbae328.png)

The server log says:

```
[2019-02-26T11:45:59.996+0100] [Payara 5.183] [SEVERE] [] [javax.enterprise.web] [tid: _ThreadID=164 _ThreadName=admin-thread-pool::admin-listener(5)] [timeMillis: 1551177959996] [levelValue: 1000] [[
  WebModule[/exist]Exception starting filter XFormsFilter
java.lang.InstantiationException
        at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:127)
.
.
Caused by: java.lang.IllegalArgumentException: URI scheme is not "file"
        at java.io.File.<init>(File.java:421)
        at de.betterform.agent.web.WebFactory.getRealPath(WebFactory.java:311)
.
.
and a bit further messages like:

  None of content dirs exist: '/home/eduard/payara5/glassfish/domains/production/applications/exist-4.6.0/WEB-INF/data/expathrepo/dashboard-1.1.0/content' and '/home/eduard/payara5/glassfish/domains/production/applications/exist-4.6.0/WEB-INF/data/expathrepo/dashboard-1.1.0/dashboard']]


```

exist log says (perhaps not related):
```
2019-02-26 11:46:03,397 [admin-thread-pool::admin-listener(5)] ERROR (MimeTable.java [load]:260) - Failed to load mime-type table from class loader
2019-02-26 11:46:03,408 [admin-thread-pool::admin-listener(5)] ERROR (MimeTable.java [load]:266) - Failed to load mime-type table from class loader
java.net.MalformedURLException: null
        at java.net.URL.<init>(URL.java:627) ~[?:1.8.0_191]
        at java.net.URL.<init>(URL.java:490) ~[?:1.8.0_191]
        at java.net.URL.<init>(URL.java:439) ~[?:1.8.0_191]
        at org.apache.xerces.impl.XMLEntityManager.setupCurrentEntity(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
        at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
        at org.exist.util.MimeTable.loadMimeTypes(MimeTable.java:290) ~[exist.jar:4.6.0]
        at org.exist.util.MimeTable.load(MimeTable.java:263) ~[exist.jar:4.6.0]
        at org.exist.util.MimeTable.load(MimeTable.java:214) ~[exist.jar:4.6.0]
```

### What did you expect
a dashboard

### Describe how to reproduce or add a test
- grab payara 5183
- grab openjdk version "1.8.0_191"
- grab exist war 4.6
- install it
- run it

**Comment by dizzzz** [comment] 2019-02-26 13:32
duplicate of https://github.com/eXist-db/exist/issues/2506 ; part of 4.6.1

note for @eduarddrenth  we do not develop/design/test explicitly for `payara5`, so you might find issues. but it should work probably?

**Closed by dizzzz** 2019-02-26 13:32 UTC
Labels: duplicate

**Comment by eduarddrenth** [comment] 2019-02-26 13:46
Thanks, I think a war should run on a servlet container of choice.

**Comment by dizzzz** [comment] 2019-02-26 14:33
@eduarddrenth you are right in a way, but not entirely.

Some things are server implementation specific; e.g. there are application servers that do not 'explode' the war file, and remove them during shutdown. We can not support these things. For us, when it runs in the reference implementation of servlets (tomcat) it is good enough.

**Comment by eduarddrenth** [comment] 2019-02-26 15:04
I understand, the war/servlet spec perhaps just doesn't garantee enough. I have good hope recent jakarta ee developments will improve here, ee 8 already did. I think it might be good to separate exist database completely from exist application development, more like rbms/connector/app and then use ee / war for the app. But that is perhaps against the integrated design and is another subject. I'll let you know about running on payara.
