### ISSUE TITLE
util:get-resource-by-absolute-id() has no result

### ISSUE THREAD

**Issue by jeti69** [eXist-db/exist#3054] opened 2019-10-16 13:14 UTC
### What is the problem
I try to get a node via its ressource id. But result is empty:

`xquery version "3.1";
let $doc := doc('/db/apps/ivd/data/IFUs_ivdr/plh/b4212/g40c_ivdr/en/ivd.xml')
let $node := $doc//data[1]/product[1]
let $doc-id as xs:integer := util:absolute-resource-id($node)

return
    (
    $node,
    $doc-id,
    count(util:get-resource-by-absolute-id($doc-id)),
    util:get-resource-by-absolute-id($doc-id)/node()
)`

@Adaptive output:
![exide-result](https://user-images.githubusercontent.com/56030773/66922456-63c8b700-f027-11e9-92b0-3772b7c2d976.png)

### Describe how to reproduce or add a test
See code above.

### Context information
- eXist-db 5.0.0
- Java8u128)
- Windows 7, 64 bit
- JAR installer

Best regards
Jens

**Comment by joewiz** [comment] 2019-10-16 13:52
Duplicate of https://github.com/eXist-db/exist/issues/3031

**Closed by joewiz** 2019-10-16 13:52 UTC
Labels: triage
