### ISSUE TITLE
eXist produces invalid html by always optimizing empty elements to be self-closing

### ISSUE THREAD

**Issue by awagner-mainz** [eXist-db/exist#4531] opened 2022-08-31 13:12 UTC
When I store a static html5 file in eXist (by uploading it via eXide's manage command) and open it (remotely in oXygen), eXist seems to have converted empty elements to self-closing ones. This produces what html calls "empty" or "void" elements for some elements which are defined as non-empty in html5:

Before (valid html):
```html
<html>
    <head>
        <title>My page</title>
        <meta name="description" data-template="app:metaDescription" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta charset="UTF-8">
        <link rel="stylesheet" type="text/css" href="resources/css/styles-combined.css">
        <link rel="icon" type="image/png" href="resources/favicons/favicon-32x32.png" sizes="32x32">
    </head>
    
    <body id="body">
        <div id="content" data-template="app:main"></div>
        <script src="resources/js/some-script.js"></script>
    </body>
</html>
```

After (invalid html):
```html
<html data-template="i18n:translate" data-template-catalogues="data/i18n">
    <head>
        <title data-template="gui:metaTitle">Work View - The School of Salamanca</title>
        <meta name="description" data-template="gui:metaDescription" content=""/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <meta charset="UTF-8"/>
        <link rel="stylesheet" type="text/css" href="resources/css/mirador-combined.css"/>
        <link rel="icon" type="image/png" href="resources/favicons/favicon-32x32.png" sizes="32x32"/>
    </head>
    
    <body id="body">
        <div id="content" data-template="app:main"/>
        <script src="resources/js/some-script.js"/>
    </body>
</html>
```

`meta` and `link` elements are empty ("void") html elements so this may be okay, but `div` and `script` are not empty ("void") elements in html. From what I can tell, many html renderers, oXygen being one of them, just ignore the forward slash in "/>" (which is helpful in the case of the `meta` and `link` tags) and just go on parsing, expecting a closing tag to come later, which leads to "unclosed" div/body and the like errors...

NB: For what it's worth: Due to a problem with eXide, I can currently no longer reproduce the above (can't upload anymore). However, in trying to install the html file in a different way, I found that if I create a new file in eXide and store it in the db, the problem does not occur ("after" is identical to "before", without self-closing elements). This seems to depend on the type of file I am creating (e.g. eXist does not allow me to store the "before" variant if I have created it as "HTML"/"HTML5 Div Using Templating", but it's okay if I am creating it as "Other"...).

**Context (please always complete the following information):**
 - OS: Ubuntu 16.04
 - eXist-db version: eXist-db 5.2.0
 - Java Version openjdk 11.0.16

**Comment by line-o** [comment] 2022-08-31 21:33
related https://github.com/eXist-db/exist/issues/2056

**Comment by line-o** [comment] 2022-08-31 21:36
Another way to reproduce the issue
(for this to actually be possible the `meta` and `link` elements are now proper XML unary tags with self closing `/`

```xquery
xmldb:store("/db", "test.html", <html>
    <head>
        <title>My page</title>
        <meta name="description" data-template="app:metaDescription" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta charset="UTF-8" />
        <link rel="stylesheet" type="text/css" href="resources/css/styles-combined.css" />
        <link rel="icon" type="image/png" href="resources/favicons/favicon-32x32.png" sizes="32x32" />
    </head>
    
    <body id="body">
        <div id="content" data-template="app:main"></div>
        <script src="resources/js/some-script.js"></script>
    </body>
</html>)
```

**Comment by line-o** [comment] 2022-08-31 21:55
Interestingly the output of the stored contents using the REST-style API does _not_ auto-close the div and script tags.
So, they are stored as empty but eXide serialises them as unary.
Please also note that we get an XML-declaration at the top.

```bash
; curl http://admin@localhost:8080/exist/rest/db/test.html
<?xml version="1.0" encoding="UTF-8"?>
<html>
    <head>
        <title>My page</title>
        <meta name="description" data-template="app:metaDescription" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta charset="UTF-8" />
        <link rel="stylesheet" type="text/css" href="resources/css/styles-combined.css" />
        <link rel="icon" type="image/png" href="resources/favicons/favicon-32x32.png" sizes="32x32" />
    </head>
    <body id="body">
        <div id="content" data-template="app:main"></div>
        <script src="resources/js/some-script.js"></script>
    </body>
</html>
```

**Comment by line-o** [comment] 2022-08-31 22:05
```xquery
xquery version "3.1";

xmldb:store("/db", "test.html",
    <html>
        <head>
            <title>My page</title>
            <meta name="description" data-template="app:metaDescription" content="" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            <meta charset="UTF-8" />
            <link rel="stylesheet" type="text/css" href="resources/css/styles-combined.css" />
            <link rel="icon" type="image/png" href="resources/favicons/favicon-32x32.png" sizes="32x32" />
        </head>
        
        <body id="body">
            <div id="content" data-template="app:main"></div>
            <script src="resources/js/some-script.js"></script>
        </body>
    </html>
)
=> doc()
=> serialize(map { "method": "html", "version": "5.0" })
```
comes very close to the desired output (with doctype and link and meta without closing `/`) but the special characters are encoded (`>` -> `&gt;`).

Replacing the call to `fn:serialize` with 

```xquery
declare namespace output="http://www.w3.org/2010/xslt-xquery-serialization";

declare option output:method "html";
declare option output:version "5.0";
```

Returns an HTML-document with no doctype div and auto-closing link and meta.

**Comment by line-o** [comment] 2022-08-31 22:07
I tested on 6.1.0-SNAPSHOT f3424d7c44d2cc7d8eb722e0701709de6e497a34

**Comment by line-o** [comment] 2022-09-01 10:24
Using the correct output option `html-version` does the trick

```
declare namespace output="http://www.w3.org/2010/xslt-xquery-serialization";

declare option output:method "html";
declare option output:html-version "5.0";
```

I can conclude that eXist-db stores the nodes unaltered (but requires all tags to be closed). The only way around that is to store the HTML file as binary. But since we are talking about a template this is not desired. The nodes need to be accessible via XQuery.

And for the auto-closing of tags: this is done by eXide and a separate, [new issue](https://github.com/eXist-db/eXide/issues/new/choose) needs to be opened for that.

**Closed by line-o** 2022-09-01 10:24 UTC
Labels: bug, investigate
