### ISSUE TITLE
xmldb:move causes IO Error in ConsistencyCheckTask

### ISSUE THREAD

**Issue by gspringtech** [eXist-db/exist#747] opened 2015-07-20 21:45 UTC
After moving a binary file using xmldb:move from a sub-collection to its parent, the ConsistencyCheckTask will throw an IO error.

To reproduce, create a collection '/db/test' with a  sub-collection '/db/test/sub'. Add a binary file to the sub-collection.
Run xmldb:move('/db/test/sub','/db/test','file.jpg') from eXide

Then run a Backup from the Dashboard.

_The error can be overcome by moving the same binary back to where it came from._

This problem affects the latest v3 rc1 as well as previous versions. First reported in 2012.

**Comment by dizzzz** [comment] 2015-08-31 12:26
I think/hope/expect it is solved with https://github.com/eXist-db/exist/pull/768

**Comment by adamretter** [comment] 2015-08-31 12:50
@dizzzz I would not expect it to be. This I suspect is related to the Journal logging of actions on binary files, of which I spotted a few problems whilst doing the above work. So I think the problem was always there and will still be there. Certainly some work needs to be done to fix/improve the Journal for binary resources...

**Comment by dizzzz** [comment] 2015-08-31 12:53
@gspringtech  ... are you running eXistdb on Windows?

**Comment by gspringtech** [comment] 2015-08-31 21:29
@dizzzz  no, deployed on CentOS 7.1 with Java 1.8.0_31 (and development on a Mac).
Can the NIO changes be pulled into 2.2?

**Comment by dizzzz** [comment] 2015-09-01 06:49
I think the merge is too large and risky...

**Comment by adamretter** [comment] 2015-09-01 09:53
@gspringtech I am using aspects of Java 8 in the NIO.2 changes that I made. eXist 2.2. is on Java 7, and I am afraid that I don't have any interest in back-porting those. Will you have a problem with moving to eXist 3.0?

**Comment by gspringtech** [comment] 2015-09-01 10:14
Looking forward to the upgrade. Is it production-ready (enough)?

**Comment by adamretter** [comment] 2015-09-01 10:23
@gspringtech There will be an RC2 shortly. Assuming that goes well, then there will be a production release. If issues are found then there will be a RC3.

**Comment by joewiz** [comment] 2016-09-20 14:19
@dizzzz @adamretter Should this issue be labeled as "bug"?

**Comment by ljo** [comment] 2016-09-21 06:27
Since this will probably not be fixed for 2.x but already is addressed by adamretter's nio.2 atomization fixes for 3.x the labeling can be a bit tricky. Bug label won't hurt though.

**Comment by joewiz** [comment] 2016-09-21 11:48
But @adamretter said in https://github.com/eXist-db/exist/issues/747#issuecomment-136362227 that his NIO changes for 3.x did not the underlying issue here - journaling of binary resources. So the bug here is still in the 3.x code, no? Also, the original report was about 3.0RC1, not 2.x. 2.x only came up in subsequent discussions about backporting #768.

**Comment by ljo** [comment] 2016-09-21 12:45
@joewiz Then I need to try another time. I had no problem with the two collections and the resource I used trying to reproduce the test routine outlined in comment 1 to get the error.

**Comment by ljo** [comment] 2016-09-21 12:52
Regarding previous versions I just responded to what is in the issue comments affecting all versions since 2012 up until 3.0-RC1. If it is not addressed, even indirectly, by the #747 the test needs some amending if I fail to reproduce it a second time.

**Comment by joewiz** [comment] 2016-09-21 12:55
Agreed, if the problem reported can't be reproduced, the issue should be closed.

**Comment by ljo** [comment] 2016-09-21 13:20
Second try, same collections different binary resource. And yet other collections different binary resource again. Both pass with head.
Could someone else counter this with a failure? Otherwise we close.

**Comment by gspringtech** [comment] 2016-09-21 22:49
I concur - tested in eXist-3.0.RC2 without error.
I also tested the copy with overwrite - no apparent problem.

**Comment by ljo** [comment] 2016-09-22 07:38
@gspringtech Great, thanks for confirming.

**Closed by ljo** 2016-09-22 07:38 UTC
