### ISSUE TITLE
Avoid indenting HTML in Exist DB

### ISSUE THREAD

**Issue by diego1a** [eXist-db/exist#460] opened 2015-02-02 12:07 UTC
I've a problem with Exist, when I save an HTML and I can´t avoid the indenting that exists makes to my HTML.(Unwanted spaces around some tags)

I tried to change the serialize ident parameter to no, the expand-xincludes to no, with the same result.

Any idea ??

Thanks in advance.

**Comment by joewiz** [comment] 2015-02-02 18:18
Is this not a duplicate of #456?

**Comment by diego1a** [comment] 2015-02-03 07:11
Yes, but with different examples and explanation and examples.

Any idea ?

**Comment by pcolot01** [comment] 2015-02-09 13:06
I am able to generate files without indentation using the XML serializing option.
If your HTML is well formed (all HTML tags ares imbricated, closed or empty),
this workaround should work. My sole problem was the hard spaces always 
saved a numerical entity. I created a local patch for my own usage to have it
saved as a UTF8 unicode character.

**Comment by diego1a** [comment] 2015-02-09 14:49
I've resolved finally with the indent parameter, finally it has work fine.

Apart that the exide editor writes with indention the file is ok.

**Comment by dizzzz** [comment] 2015-02-25 07:58
'indent' parameter ...... wehere did you set this?

**Closed** 2015-02-25 17:01 UTC
Labels: question
