### ISSUE TITLE
Issue with attributes

### ISSUE THREAD

**Issue by windauer** [eXist-db/exist#923] opened 2016-02-29 14:13 UTC
Following query return also TEI:blibl elements with types different to linguistic (e.g. 'auxiliary')

``` xquery
collection('/db/apps/lgpn-data/data/ling/names')//TEI:orth[.='Agathōnymos']/ancestor::TEI:entry//TEI:bibl[@type = 'linguistic']
```

if the query is split like this:  

``` xquery
let $bibls  := collection('/db/apps/lgpn-data/data/ling/names')//TEI:orth[.='Agathōnymos']/ancestor::TEI:entry//TEI:bibl
return $bibls[@type = 'linguistic']
```

the results are as expected. 

I can provide access to a server demonstrating this issue if someone wants to have a look and fix it.

**Comment by dizzzz** [comment] 2016-02-29 14:26
optimizer issue?

**Comment by ljo** [comment] 2016-02-29 14:29
Or too lazy evaluation. I can reproduce it so no need for access.

**Comment by dizzzz** [comment] 2016-04-18 10:33
@wolfgangmm have you seen /talked about this ?

**Comment by tuurma** [comment] 2017-01-06 13:32
I have another case (mentioned above) which I don't have time to properly isolate atm but looks the underlying problem may be identical to this one so happy to test after this issue is fixed.

**Comment by wolfgangmm** [comment] 2018-10-15 08:28
Closing because it seems to have been fixed along the way.

**Closed by wolfgangmm** 2018-10-15 08:28 UTC
Labels: bug
