### ISSUE TITLE
Map operator on array causes XPathException

### ISSUE THREAD

**Issue by adamretter** [eXist-db/exist#1186] opened 2016-11-28 16:51 UTC
The following query should return the sequence `("editors", "readers", "executioners", "devs")` however in eXist it throws an `XPathException` with the message `exerr:ERROR cannot convert map('') to a node set`:

```xquery
xquery version "3.1";

let $configs := (
    map {
        "name": "thing1",
        "user-groups": (
            map {
                "name": "editors",
                "perm": "rwx"
            },
            map {
                "name": "readers",
                "perm": "r-x"
            }
        )
    },
    map {
        "name": "thing2",
        "user-groups": (
            map {
                "name": "executioners",
                "perm": "r-x"
            },
            map {
                "name": "devs",
                "perm": "rwx"
            }
        )
    }
) return

for $config in $configs
let $user-groups := $config("user-groups")
return
	$user-groups ! .("name")
```

**Comment by duncdrum** [comment] 2019-01-10 12:48
@adamretter could you provide a test PR with a pending test please, thx.

**Comment by line-o** [comment] 2020-04-09 09:12
duplicate of https://github.com/eXist-db/exist/issues/3240

**Closed** 2020-04-09 09:12 UTC
Labels: bug, duplicate, xquery
