### ISSUE TITLE
Spatial module doesn't build

### ISSUE THREAD

**Issue by gtnewton** [eXist-db/exist#49] opened 2013-09-19 17:52 UTC
Environment: ubuntu 13.04 64-bit, OpenJDK 7, latest exist from git

Steps to reproduce:
1) Activate spatial module in $build-dir/extensions/indexes/local.build.properties
2) ./build.sh download-additional-jars
3) ./build.sh all

The end of the compile looks like this

```
compile-src:
     [echo] Compiling sources 'index-spatial'
    [mkdir] Created dir: /home/gtn/exist/extensions/indexes/spatial/build/classes
    [javac] Compiling 10 source files to /home/gtn/exist/extensions/indexes/spatial/build/classes
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.6
    [javac] /home/gtn/exist/extensions/indexes/spatial/src/org/exist/indexing/spatial/GMLHSQLIndexWorker.java:61: error: GMLHSQLIndexWorker is not abstract and does not override abstract method getQueryRewriter(XQueryContext) in IndexWorker
    [javac] public class GMLHSQLIndexWorker extends AbstractGMLJDBCIndexWorker {
    [javac]        ^
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] 1 error
    [javac] 1 warning

BUILD FAILED
/home/gtn/exist/build/scripts/build-impl.xml:415: The following error occurred while executing this line:
/home/gtn/exist/build/scripts/extensions-build.xml:31: The following error occurred while executing this line:
/home/gtn/exist/build/scripts/extensions-common.xml:137: The following error occurred while executing this line:
/home/gtn/exist/build/scripts/extensions-common.xml:199: The following error occurred while executing this line:
/home/gtn/exist/build/scripts/extensions-common.xml:152: The following error occurred while executing this line:
/home/gtn/exist/build/scripts/extensions-common.xml:163: Compile failed; see the compiler error output for details.
```

Also, note that the fetch url in $build-dir/extensions/indexes/spatial/extension.xml pointing to geoapi-nogenerics-2.1.1.jar (line 19) gets a 404. The file is available at the osgeo.org location used elsewhere in the file.

**Comment by joewiz** [comment] 2017-02-05 02:13
Close as a dupe of the more recently verified/labeled/decided on #306?

**Closed** 2017-02-06 12:20 UTC
Labels: bug
