### ISSUE TITLE
[BUG] XQuery parser fails to parse `document{}`

### ISSUE THREAD

**Issue by adamretter** [eXist-db/exist#4446] opened 2022-06-15 09:40 UTC
The XQuery parser should parse the following expression:

```xquery
document{}
```

Instead it fails with the error:

```
err:XPST0003 Syntax error: unexpected token: }
```

You can workaround this by using: `document{()}`

Tested against eXist-db 6.0.1

**Comment by line-o** [comment] 2022-11-01 07:45
Duplicate of #4593
Closing this one because the other has more info in it.

**Closed by line-o** 2022-11-01 07:45 UTC
Labels: bug, parser, xquery
