### ISSUE TITLE
Missing elements when using descendant-or-self

### ISSUE THREAD

**Issue by mjhallman** [eXist-db/exist#1464] opened 2017-06-23 19:56 UTC
```xquery
let $block :=
<a>
    <z>
        <b></b>
    </z>
    <c>
        <b></b>
    </c>
</a>

return $block//*[name(.) eq 'b'][1]
```

This only returns 1 `<b>` element in eXist-db. It should return both `<b>` elements.
I have tested this in BaseX and Saxon and they are correct, whereas eXist-db is not.

**Comment by dizzzz** [comment] 2017-06-23 20:03
please fill in the issue-template. It makes sure you'll add all required information, info we need to understand the exact context. thnx

**Comment by adamretter** [comment] 2017-06-23 20:16
@dizzzz I helped @mjhallman report these. Everything that is needed to reproduce is there.

**Comment by dizzzz** [comment] 2017-06-23 20:20
one essential thing for this issue: a hint missing regarding the eXist-db version.

**Comment by adamretter** [comment] 2017-06-23 20:25
@dizzzz Ah okay, my bad. It's the `HEAD` of the `develop` branch.

**Comment by duncdrum** [comment] 2019-01-11 10:39
duplicate of  #798

**Closed by duncdrum** 2019-01-11 10:39 UTC
Labels: bug, duplicate
