### ISSUE TITLE
[BUG]collection renaming corrupts collection over WebDAV

### ISSUE THREAD

**Issue by nsincaglia** [eXist-db/exist#3371] opened 2020-04-15 19:52 UTC
eXist Version: | 5.2.0
eXist Build: | 20200123133609
Operating System: | Linux 4.14.165-133.209.amzn2.x86_64 amd64
Java Version: | 11.0.5
Default Encoding: | UTF8
Instance ID: | exist
System CPU Load: | 0.00672646
Process CPU Load: | 0.00448430
Free Physical Memory: | 8846880768
Total Physical Memory: | 16624488448

**Describe the bug**
When one tries to rename a collection using WebDAV, an error is thrown and the collection gets corrupted. There is no way to delete the collection after it is corrupted and all data and sub-collections are no longer accessible.

The errors that I saw within the exist.log are:
020-04-13 04:03:55,400 [qtp1916303325-27] WARN  (Descriptor.java [<init>]:116) - Giving up unable to read descriptor.xml file from classloader in package org.exist.http, eXist-db Core, version 5.2
2020-04-13 04:04:50,259 [qtp1916303325-32] WARN  (TransactionManager.java [close]:409) - Transaction was not committed or aborted, auto aborting!

When I looked the reported errors in my WebDAV client application (Panic Software Transmit) are:
Delete PADPIDA2017091801T-PADPIDA2015030501F

org.xmldb.api.base.XMLDBException: Failed to invoke method removeCollection in class org.exist.xmlrpc.RpcConnection: null
Failed to invoke method removeCollection in class org.exist.xmlrpc.RpcConnection: null

ro.sync.db.b.m: org.xmldb.api.base.XMLDBException: Failed to invoke method removeCollection in class org.exist.xmlrpc.RpcConnection: null
    at ro.sync.db.nxd.exist.d.d(Unknown Source)
    at ro.sync.db.nxd.exist.e.ah(Unknown Source)
    at ro.sync.db.nxd.d.nh(Unknown Source)
    at ro.sync.db.nxd.d$3.cli(Unknown Source)
    at ro.sync.db.f.z.cyp(Unknown Source)
    at ro.sync.db.f.z$1.dxd(Unknown Source)
    at ro.sync.ui.application.mb.run(Unknown Source)
Caused by: org.xmldb.api.base.XMLDBException: Failed to invoke method removeCollection in class org.exist.xmlrpc.RpcConnection: null
    at org.exist.xmldb.RemoteCollectionManagementService.removeCollection(RemoteCollectionManagementService.java:140)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    ... 7 more
Caused by: org.apache.xmlrpc.XmlRpcException: Failed to invoke method removeCollection in class org.exist.xmlrpc.RpcConnection: null
    at org.apache.xmlrpc.client.XmlRpcStreamTransport.readResponse(XmlRpcStreamTransport.java:197)
    at org.apache.xmlrpc.client.XmlRpcStreamTransport.sendRequest(XmlRpcStreamTransport.java:156)
    at org.apache.xmlrpc.client.XmlRpcHttpTransport.sendRequest(XmlRpcHttpTransport.java:143)
    at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.sendRequest(XmlRpcSunHttpTransport.java:69)
    at org.apache.xmlrpc.client.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:56)
    at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:167)
    at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:158)
    at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:147)
    at org.exist.xmldb.RemoteCollectionManagementService.removeCollection(RemoteCollectionManagementService.java:138)
    ... 11 more

**Comment by joewiz** [comment] 2020-04-15 20:22
@nsincaglia Which version of Transmit?

**Comment by nsincaglia** [comment] 2020-04-15 20:52
Version 5.6.3 (149563)

**Comment by adamretter** [comment] 2020-04-15 21:26
@nsincaglia  two issues were recently addressed in this area:

1. https://github.com/eXist-db/exist/issues/3310
2. https://github.com/eXist-db/exist/issues/3040

Would you be able to test your issue with a build of 5.3.0-SNAPSHOT ?

**Comment by xatapult** [comment] 2020-04-16 06:37
It's not only through webdav but also through XML-RPC (I was using a native oXygen connection with the db)

**Comment by adamretter** [comment] 2020-04-16 08:16
@xatapult indeed - the issue that I fixed was in the storage layer, and so it would have affected all APIs

**Comment by dizzzz** [comment] 2020-04-16 09:45
SO..... "webdav" is not valid in the title?

**Comment by adamretter** [comment] 2020-04-16 10:04
@dizzzz It might be! I am only saying that - the issue I fixed, affected all APIs. Until someone can verify that that fixed this reported issue, we can't be sure it is the same thing ;-)
Hopefully @nsincaglia and @xatapult will report their findings against 5.3.0-SNAPSHOT soon.

**Comment by brianlynn1** [comment] 2020-08-19 17:36
I have what appears to be the same issue using eXide.  (under 52.0, running on Debian).

I created an application collection with various subcollections as usual (modules, resources, resources/css, etc.) by copying the contents of an existing application collection (that I had created).  Then I decided to change the name of application collection.   Result:  Collection name is changed, but child collections are lost.  But they can't be re-added - the collection is corrupted.   Futzing around with that collection, e.g. trying to repaste the child collections, or trying to delete the new collection, doesn't work, generating various errors and lockups in the exist-db log, and eventually crashing/locking up the server, requiring a kill -9 to stop it and restart..  This happened at least twice. (I didn't believe it the first time.) As it's a UAT / semi-production server I didn't want to mess around any more.

I was pretty surprised as renaming a collection seems like a pretty basic operation.   (I  had related issues trying to install new application code versions by using load-files-from-pattern, which also locked up the server... it makes me very leery of changing the application software.  Is that a known issue?)

Is this issue expected to be resolved in 5.3.0?

**Comment by adamretter** [comment] 2020-08-20 10:51
@brianlynn1 I think so. Perhaps @xatapult @nsincaglia or @dizzzz can confirm?

**Comment by xatapult** [comment] 2020-08-20 11:02
@adamretter What do you want me to confirm? Yes it's a bug...

**Comment by adamretter** [comment] 2020-08-20 11:25
@xatapult I was looking for someone to confirm that the issue is fixed in 5.3.0-SNAPSHOT

**Comment by nsincaglia** [comment] 2020-08-20 12:30
Yes, I can confirm that this issue is resolved in 5.3.0-SNAPSHOT.NickNick Sincaglia President/FounderNueMeta, LLCDigital Media & TechnologyPhone: +1-630-303-7035nsincaglia@nuemeta.com http://www.nuemeta.comSkype: nsincaglia
-------- Original message --------From: Adam Retter <notifications@github.com> Date: 8/20/20  6:25 AM  (GMT-06:00) To: eXist-db/exist <exist@noreply.github.com> Cc: nsincaglia <nsincaglia@nuemeta.com>, Mention <mention@noreply.github.com> Subject: Re: [eXist-db/exist] [BUG]collection renaming corrupts collection
  over WebDAV (#3371) 
@xatapult I was looking for someone to confirm that the issue is fixed in 5.3.0-SNAPSHOT

**Comment by brianlynn1** [comment] 2020-08-20 16:19
Thank you very much!

**Closed** 2020-08-20 16:33 UTC
Labels: triage
