### ISSUE TITLE
Launcher not working in eXist 5.2

### ISSUE THREAD

**Issue by jmcneal9** [eXist-db/exist#3357] opened 2020-04-10 20:47 UTC
**Describe the bug**
eXist 5.2 will not start when run from the launcher

**Expected behavior**
eXist 5.2 should start when run from the launcher

**To Reproduce**
Have java installed in it's default location under Program Files (in my case, C:\Program Files\Java\jre1.8.0_201\bin\javaw.exe)

Have eXist installed at a location that is a few folders deep (in my case, C:\development\utilities\eXist-5.2.0)

**Screenshots**
![image](https://user-images.githubusercontent.com/55259199/79021681-cebffa00-7b41-11ea-8252-5745a4d6bed7.png)

**Context (please always complete the following information):**
 - OS: Windows 8.1 (64-bit)
 - eXist-db version: 5.2.0
 - Java Version: Java 1.8.0_201

**Additional context**
- How is eXist-db installed? JAR
- Any custom changes in e.g. `conf.xml`? None
- Note: Can still launch eXist from startup.bat at least
- Related link? https://stackoverflow.com/questions/10519558/createprocess-error-206-the-filename-or-extension-is-too-long-when-running-main

**Comment by adamretter** [comment] 2020-04-11 12:24
This is a duplicate of #3276 

@jmcneal9 Could you take a look at #3276 and let us know if you think PowerShell alternatives to the .bat files could work for you?

**Closed by adamretter** 2020-04-11 12:24 UTC
Labels: investigate, windows
