### ISSUE TITLE
Incomprehensible warning messages in exist.log

### ISSUE THREAD

**Issue by xatapult** [eXist-db/exist#2622] opened 2019-04-02 13:50 UTC
### What is the problem
Nothing goes wrong but we get a lot of messages in the exist.log like these:

```
2019-04-02 15:34:42,729 [qtp1430358188-50914] WARN  (PathExpr.java [replace]:119) - Expression not found: $jblogin:key-db-username-column; in: false() 
2019-04-02 15:34:42,729 [qtp1430358188-50914] WARN  (PathExpr.java [replace]:119) - Expression not found: $jblogin:key-db-password-column; in: false() 
2019-04-02 15:34:42,729 [qtp1430358188-50914] WARN  (PathExpr.java [replace]:119) - Expression not found: $jblogin:key-db-exist-user; in: false() 
```

There are lots and lots of them. I tried to find out what they refer to but couldn't.

Sometimes it seems that eXist is warning me for a lookup in a map on a key that doesn't exist, but why should it? 

### What did you expect
I see no reason why eXist would warn me. The code runs ok, no errors.

### Describe how to reproduce or add a test
That's a problem, this is produced by a huge code base that isn't really portable. And I have no idea what exactly causes this. I'm sorry I cant be of more help here.

I suppose (?) that it is possible to look in the code and find out at least where and why this message is produced?

### Context information
Please always add the following information
- eXist-db version + Git Revision: 4.4.0 (Build 201809300841) 
- Java version 1.8.0.191_b12
- Operating system Windows server 2012
-  64 bit
- How is eXist-db installed? (JAR installer)
- Any custom changes? only memory settings

**Comment by duncdrum** [comment] 2019-04-03 12:44
@eriksiegel I m not sure how we could be of help here. If you can't locate the variables mentioned in the warning message, and we don't have code to run. 

Have you tried to increase the logger level to see if further information can be glanced from the logs? What about timing, can you install the app on an isolated system and take note of the timing of event? Lastly, map lookup failures could be related to the html templating, maybe empty form fields are submitted without the underlying xquery code designed to handle empty inputs?

**Comment by eriksiegel** [comment] 2019-04-03 13:36
@duncdrum I know its difficult. But isn't it possible by looking into the code to at least find out *why* this particular warning is generated and what it means? It must be generated somewhere and someone once thought there was a good reason for it... Maybe you can have a look in the code (search on parts of the error message text?), I'll try to isolate the damned thing.

- The variables mentioned in the message can be located, sure. They're in the code, liud and clear. But I can't find anything wrong in their usage, let alone something eXist should be warning me about.
- No I haven't fiddled with the logger level yet
- Timing? It happens when some query runs
- We don't use HTML templating

Anyway, if we can't resolve or clear up anything, its ok. It all runs without glitches. 

However emitting incomprehensible warning messages, filling up the log with nonsense, eating system resources in doing this, confusing users that access the log, sounds like a bug te me, although not a fatal one.

**Comment by duncdrum** [comment] 2019-04-03 13:48
well to evaluate if these warnings are actually issued in error, we need code to reproduce the warnings. 

All i can see is that some code is looking for `$jblogin:key-db-username-column` and two other variables in a place where they cannot be found. By itself this looks like a sensible warning message to put into the logs. 

If you can identify the query that produces these warnings, you could try to wiggle it down to give us a reproducible example. Even if your code is working, the warnings could still be accurate and not point to a problem with exist's loggers/error handling.

**Comment by eriksiegel** [comment] 2019-04-03 15:06
I tried several things but I cant nail it down. I did notice that these errors seemed also to show up for code that wasn't executing at the time. Weird...

>All i can see is that some code is looking for $jblogin:key-db-username-column and two other variables in a place where they cannot be found. By itself this looks like a sensible warning message to put into the logs.

But if that was the case, shouldn't I get some XQuery *error* ?

And whether the message is "sensible": If you can't link a message to some location/event, it might be a correct message, but it's only confusing. Technical correctness is not the only thing that matters about messages...

Sorry I cant be of more help in locating the cause. Maybe we should just close this issue, we can live with it.

**Comment by adamretter** [comment] 2019-04-08 07:39
@eriksiegel It looks like some sort of bad optimization as part of the query rewriting, I think only @wolfgangmm could comment on this, as I believe he implemented the query rewriting.

**Comment by duncdrum** [comment] 2019-04-27 10:55
Unless someone has any bright ideas, i m afraid there isn't enough in here for us to be of help. Will close in 2 weeks

**Comment by adamretter** [comment] 2019-04-27 15:44
@duncdrum Well I think @wolfgangmm could comment on this, which would be helpful...

**Comment by adamretter** [comment] 2019-05-21 15:42
@eriksiegel By chance, I saw this message in the logs for some of eXist-db's XQuery tests. From that, I was able to create a small reproducible test case. The problem isn't just on Windows it also happens on my Mac:

This very small reproducible test case will cause the warning from line `117 of` PathExpr.java` to be printed to `exist.log`:

```
xquery version "3.1";

module namespace enf="http://exist-db.org/xquery/test/expr-not-found";
declare namespace test="http://exist-db.org/xquery/xqsuite";

declare variable $enf:static := 'I am static.';

declare
    %test:assertEquals('I am static.')
function enf:read-static () {
    $enf:static
};
```

The warning looks like:
```
2019-05-21 19:41:33,312 [main] WARN  (PathExpr.java [replace]:119) - Expression not found: $enf:static; in: enf:read-static() item()* 
```

So, @wolfgangmm could you take a look please?

**Comment by eriksiegel** [comment] 2019-05-22 04:58
@adamretter Great! So it has something to do with accessing variables declared with `declare variable`? I think in retrospect that makes sense, the messages we got were usually (always?) about statically declared maps.

**Comment by adamretter** [comment] 2019-05-22 06:09
Yes, but I think it might only be when this happens in library modules

**Comment by wolfgangmm** [comment] 2019-05-22 06:42
The message is generated during the query optimization step, indicating that certain rewrites were not possible. It has no negative effect and should likely be sent to DEBUG or TRACE instead of WARN. I'll have a look later today.

**Comment by xatapult** [comment] 2020-01-09 13:36
Hi. We're now running 4.7.1 and and probably because of the way we set up the modules the message appear over and over and over again. Its impacting performance.  Anything we can do? Is this solved in 5.x?

**Comment by adamretter** [comment] 2020-01-09 14:29
@xatapult The issue is in both 4.x.x and 5.x.x. Could you try this patch:

```
diff --git a/exist-core/src/main/java/org/exist/xquery/PathExpr.java b/exist-core/src/main/java/org/exist/xquery/PathExpr.java
index 183bdbd5a0..5552fd00ec 100644
--- a/exist-core/src/main/java/org/exist/xquery/PathExpr.java
+++ b/exist-core/src/main/java/org/exist/xquery/PathExpr.java
@@ -116,7 +116,9 @@ public class PathExpr extends AbstractExpression implements CompiledXQuery,
     public void replace(final Expression oldExpr, final Expression newExpr) {
         final int idx = steps.indexOf(oldExpr);
         if (idx < 0) {
-            LOG.warn("Expression not found: " + ExpressionDumper.dump(oldExpr) + "; in: " + ExpressionDumper.dump(this));
+            if (LOG.isTraceEnabled()) {
+                LOG.trace("Expression not found when trying to replace: " + ExpressionDumper.dump(oldExpr) + "; in: " + ExpressionDumper.dump(this));
+            }
             return;
         }
         steps.set(idx, newExpr);
@@ -140,7 +142,9 @@ public class PathExpr extends AbstractExpression implements CompiledXQuery,
     public void remove(final Expression oldExpr) {
         final int idx = steps.indexOf(oldExpr);
         if (idx < 0) {
-            LOG.warn("Expression to remove not found: " + ExpressionDumper.dump(oldExpr) + "; in: " + ExpressionDumper.dump(this));
+            if (LOG.isTraceEnabled()) {
+                LOG.trace("Expression not found when trying to remove: " + ExpressionDumper.dump(oldExpr) + "; in: " + ExpressionDumper.dump(this));
+            }
             return;
         }
         steps.remove(idx);
```

**Comment by xatapult** [comment] 2020-01-09 14:35
@adamretter Sorry, you have to help me here. What do I need to do exactly to apply the patch?

**Closed** 2020-01-16 09:16 UTC
Labels: bug
