### ISSUE TITLE
Serializer indention doesn't work

### ISSUE THREAD

**Issue by diego1a** [eXist-db/exist#461] opened 2015-02-02 15:08 UTC
I am running the following query:

```xquery
xmldb:store('/db/apps/demo', 'index.html', <div><div>kakakakaka</div><div>papapapap</div></div>)
```
What I expect to have in the document is:

```xml
<div><div>kakakakaka</div><div>papapapap</div></div>
```

But instead I have:

```xml
<div>
    <div>kakakakaka</div>
    <div>papapapap</div>
</div>
```
How is that, and how can I have the former instead of the latter?

(I have tried to set `<serializer indent="no">` in conf.xml, but I guess the
serializer is not involved here.)

**Comment by joewiz** [comment] 2015-02-02 18:18
Is this not a duplicate of #456?

**Comment by diego1a** [comment] 2015-02-03 07:13
Yes, but with different explanation and example, so there is not answer to this problem ?

Thanks.

**Comment by diego1a** [comment] 2015-02-09 14:49
I've resolved finally with the indent parameter, finally it has work fine.

Apart that the exide editor writes with indention the file is ok.

**Comment by dizzzz** [comment] 2015-02-25 07:57
close issue?

**Closed** 2015-02-25 17:01 UTC
Labels: duplicate
