### ISSUE TITLE
Infinite loop copying 2 xqueries to collection using oxygen.

### ISSUE THREAD

**Issue by agucabral21** [eXist-db/exist#1182] opened 2016-11-18 18:01 UTC
This happens when i try to copy (using oxygen developer) 2 .xquery files (both of them import each other).

Here is the restxq.log:

```
2016-11-17 14:32:29,515 [eXistThread-664] INFO  (ExistXqueryRegistry.java [reexamineModulesWithResolvedDependencies]:287) - Missing dependency '/db/mdm-offer/apps/price-editor/modules/priceList/refresh-priceList.xquery' has been added to the database, re-examining '/db/mdm-offer/apps/price-editor/modules/priceList/manage-priceList.xquery'...
2016-11-17 14:32:32,376 [eXistThread-664] INFO  (ExistXqueryRegistry.java [reexamineModulesWithResolvedDependencies]:287) - Missing dependency '/db/mdm-offer/apps/price-editor/modules/priceList/manage-priceList.xquery' has been added to the database, re-examining '/db/mdm-offer/apps/price-editor/modules/priceList/refresh-priceList.xquery'...
2016-11-17 14:32:34,707 [eXistThread-664] INFO  (ExistXqueryRegistry.java [reexamineModulesWithResolvedDependencies]:287) - Missing dependency '/db/mdm-offer/apps/price-editor/modules/priceList/refresh-priceList.xquery' has been added to the database, re-examining '/db/mdm-offer/apps/price-editor/modules/priceList/manage-priceList.xquery'...
2016-11-17 14:32:37,531 [eXistThread-664] INFO  (ExistXqueryRegistry.java [reexamineModulesWithResolvedDependencies]:287) - Missing dependency '/db/mdm-offer/apps/price-editor/modules/priceList/manage-priceList.xquery' has been added to the database, re-examining '/db/mdm-offer/apps/price-editor/modules/priceList/refresh-priceList.xquery'...
2016-11-17 14:32:39,843 [eXistThread-664] INFO  (ExistXqueryRegistry.java [reexamineModulesWithResolvedDependencies]:287) - Missing dependency '/db/mdm-offer/apps/price-editor/modules/priceList/refresh-priceList.xquery' has been added to the database, re-examining '/db/mdm-offer/apps/price-editor/modules/priceList/manage-priceList.xquery'...
2016-11-17 14:32:42,635 [eXistThread-664] INFO  (ExistXqueryRegistry.java [reexamineModulesWithResolvedDependencies]:287) - Missing dependency '/db/mdm-offer/apps/price-editor/modules/priceList/manage-priceList.xquery' has been added to the database, re-examining '/db/mdm-offer/apps/price-editor/modules/priceList/refresh-priceList.xquery'...
2016-11-17 14:32:44,909 [eXistThread-664] INFO  (ExistXqueryRegistry.java [reexamineModulesWithResolvedDependencies]:287) - Missing dependency '/db/mdm-offer/apps/price-editor/modules/priceList/refresh-priceList.xquery' has been added to the database, re-examining '/db/mdm-offer/apps/price-editor/modules/priceList/manage-priceList.xquery'...
2016-11-17 14:32:47,916 [eXistThread-664] INFO  (ExistXqueryRegistry.java [reexamineModulesWithResolvedDependencies]:287) - Missing dependency '/db/mdm-offer/apps/price-editor/modules/priceList/manage-priceList.xquery' has been added to the database, re-examining '/db/mdm-offer/apps/price-editor/modules/priceList/refresh-priceList.xquery'...
2016-11-17 14:32:50,242 [eXistThread-664] INFO  (ExistXqueryRegistry.java [reexamineModulesWithResolvedDependencies]:287) - Missing dependency '/db/mdm-offer/apps/price-editor/modules/priceList/refresh-priceList.xquery' has been added to the database, re-examining '/db/mdm-offer/apps/price-editor/modules/priceList/manage-priceList.xquery'...
2016-11-17 14:32:53,051 [eXistThread-664] INFO  (ExistXqueryRegistry.java [reexamineModulesWithResolvedDependencies]:287) - Missing dependency '/db/mdm-offer/apps/price-editor/modules/priceList/manage-priceList.xquery' has been added to the database, re-examining '/db/mdm-offer/apps/price-editor/modules/priceList/refresh-priceList.xquery'...
2016-11-17 14:32:55,441 [eXistThread-664] INFO  (ExistXqueryRegistry.java [reexamineModulesWithResolvedDependencies]:287) - Missing dependency '/db/mdm-offer/apps/price-editor/modules/priceList/refresh-priceList.xquery' has been added to the database, re-examining '/db/mdm-offer/apps/price-editor/modules/priceList/manage-priceList.xquery'...
2016-11-17 14:32:58,245 [eXistThread-664] INFO  (ExistXqueryRegistry.java [reexamineModulesWithResolvedDependencies]:287) - Missing dependency '/db/mdm-offer/apps/price-editor/modules/priceList/manage-priceList.xquery' has been added to the database, re-examining '/db/mdm-offer/apps/price-editor/modules/priceList/refresh-priceList.xquery'...
2016-11-17 14:33:00,508 [eXistThread-664] INFO  (ExistXqueryRegistry.java [reexamineModulesWithResolvedDependencies]:287) - Missing dependency '/db/mdm-offer/apps/price-editor/modules/priceList/refresh-priceList.xquery' has been added to the database, re-examining '/db/mdm-offer/apps/price-editor/modules/priceList/manage-priceList.xquery'...
2016-11-17 14:33:03,287 [eXistThread-664] INFO  (ExistXqueryRegistry.java [reexamineModulesWithResolvedDependencies]:287) - Missing dependency '/db/mdm-offer/apps/price-editor/modules/priceList/manage-priceList.xquery' has been added to the database, re-examining '/db/mdm-offer/apps/price-editor/modules/priceList/refresh-priceList.xquery'...
2016-11-17 14:33:05,554 [eXistThread-664] INFO  (ExistXqueryRegistry.java [reexamineModulesWithResolvedDependencies]:287) - Missing dependency '/db/mdm-offer/apps/price-editor/modules/priceList/refresh-priceList.xquery' has been added to the database, re-examining '/db/mdm-offer/apps/price-editor/modules/priceList/manage-priceList.xquery'...
2016-11-17 14:33:08,378 [eXistThread-664] INFO  (ExistXqueryRegistry.java [reexamineModulesWithResolvedDependencies]:287) - Missing dependency '/db/mdm-offer/apps/price-editor/modules/priceList/manage-priceList.xquery' has been added to the database, re-examining '/db/mdm-offer/apps/price-editor/modules/priceList/refresh-priceList.xquery'...
2016-11-17 14:33:10,638 [eXistThread-664] INFO  (ExistXqueryRegistry.java [reexamineModulesWithResolvedDependencies]:287) - Missing dependency '/db/mdm-offer/apps/price-editor/modules/priceList/refresh-priceList.xquery' has been added to the database, re-examining '/db/mdm-offer/apps/price-editor/modules/priceList/manage-priceList.xquery'...
2016-11-17 14:33:13,419 [eXistThread-664] INFO  (ExistXqueryRegistry.java [reexamineModulesWithResolvedDependencies]:287) - Missing dependency '/db/mdm-offer/apps/price-editor/modules/priceList/manage-priceList.xquery' has been added to the database, re-examining '/db/mdm-offer/apps/price-editor/modules/priceList/refresh-priceList.xquery'...
2016-11-17 14:33:15,874 [eXistThread-664] INFO  (ExistXqueryRegistry.java [reexamineModulesWithResolvedDependencies]:287) - Missing dependency '/db/mdm-offer/apps/price-editor/modules/priceList/refresh-priceList.xquery' has been added to the database, re-examining '/db/mdm-offer/apps/price-editor/modules/priceList/manage-priceList.xquery'...
2016-11-17 14:33:18,647 [eXistThread-664] INFO  (ExistXqueryRegistry.java [reexamineModulesWithResolvedDependencies]:287) - Missing dependency '/db/mdm-offer/apps/price-editor/modules/priceList/manage-priceList.xquery' has been added to the database, re-examining '/db/mdm-offer/apps/price-editor/modules/priceList/refresh-priceList.xquery'...

```

And it goes on and on... i have to shut down exist to then try to recover the db and usually this takes a lot of time....

Im using exist 2.2 , java version "1.7.0_72", <oXygen/> XML Developer 18.0, build 2016051118

**Comment by joewiz** [comment] 2016-11-18 18:55
I assume this is just a bug report, right?  You've been able to workaround the issue by avoiding mutually importing modules?

**Comment by agucabral21** [comment] 2016-11-22 14:05
I solve it removing the importation in one of the files and changing some xqueries, but i thought i should tell you about it, cause sometimes the database crashes and it really takes a time to recover from this error

**Comment by joewiz** [comment] 2016-11-22 14:21
This issue was reported with a test case by @christophe-g on the exist-open mailing list in April 2013: http://markmail.org/message/jmftuswia4icviht.

@adamretter Do you know if this has been fixed in post-2.2 development, or would it be helpful to develop Christophe's report into an issue here for further investigation?

**Comment by telic** [comment] 2017-02-24 12:42
duplicate of #1010

**Comment by dizzzz** [comment] 2017-02-24 13:07
could you provide a small testcase?

**Comment by duncdrum** [comment] 2019-01-10 12:44
closing as duplicate please continue the discussion in #1010

**Closed by duncdrum** 2019-01-10 12:44 UTC
Labels: bug, duplicate
