### ISSUE TITLE
http error 500 Problem accessing /exist/apps/dashboard. Reason server error

### ISSUE THREAD

**Issue by Lourido** [eXist-db/exist#1866] opened 2018-05-11 18:56 UTC
Thank you for reporting your issue!

To be able to better understand you problem or suggestion, please add as much information as possible to this ticket. When there is no or just little information, it will be too difficult to work on it (and hence we will not be able to solve it)

Please fill in the following sections:

### What is the problem
> Describe exactly what you see (e.g. an output of an XQuery) 
After disabling Gatekeeper from Mac OS Sierra 10.12.6, 64 bit, I've tried to install exist-db 4.1.0.
Java version: 10.0.1
During the installation I've got the error message 
![exist-db error](https://user-images.githubusercontent.com/23460076/39941534-200836f0-555d-11e8-94f9-cf4e4d83261a.jpeg)

When I tried to access the dashboard I've got the error message mention on top, with the following details:
[exist-db Error 500 Server Error.pdf](https://github.com/eXist-db/exist/files/1996492/exist-db.Error.500.Server.Error.pdf)

### What did you expect
> Describe what you expected to happen. Add for example a reference to a [specification](https://www.w3.org/TR/xquery-3/).

I wish I could install exist-db properly cause I need it.

### Describe how to reproduce or add a test
> Describe how we can can reproduce the problem.

I guess if you try in a Mac OS Sierra you'll get the same result. 

> The *best* way is to provide a 'self containing' test, a test that can be run without dependancies. The [XQSuite - Annotation-based Test Framework for XQuery](http://exist-db.org/exist/apps/doc/xqsuite.xml) makes it very easy for you to create tests. These tests can be executed from the [eXide editor](http://exist-db.org/exist/apps/eXide/index.html) (XQuery - Run as Test)

### Context information
Please always add the following information
- eXist-db version + Git Revision hash e.g. eXist-db 3.0 /  acd0c14 
- Java version (e.g. Java8u121)
- Operating system (Windows 7, Linux, MacOs)
- 32 or 64 bit
- Any custom changes in e.g. conf.xml

**Comment by duncdrum** [comment] 2018-05-11 19:05
Running the installer with Java10 is currently not supported, you ll need to install Java8 and make sure that your system's JAVA_HOME property is pointing to it (you might have to relog for changes to take effect) 

duplicate of #1792

**Closed** 2018-05-11 19:25 UTC
Labels: duplicate

**Comment by Lourido** [comment] 2018-05-12 08:59
Thanks a lot, duncdrum, dizzzz!!!! 👌
