### ISSUE TITLE
Hang of database

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/exist#1741] opened 2018-02-20 15:56 UTC
### What is the problem
The database hanged twice this week while Bulk uploading data via REST/PUT , and while accessing a dashboard application. Typical log in std out during shutdown (no full stack captured :-( )

```
2018-02-20 16:21:06,834 [DefaultQuartzScheduler_Worker-1] INFO  (NativeBroker.java [sync]:3670) - Memory: 1,683,968K total; 1,864,192K max; 359,987K free 
2018-02-20 16:21:06,834 [DefaultQuartzScheduler_Worker-1] INFO  (BTree.java [printStatistics]:2619) - dom.dbx INDEX Buffers occupation : 100% (12442 out of 12442) Cache efficiency : 99% 
2018-02-20 16:21:06,834 [DefaultQuartzScheduler_Worker-1] INFO  (DOMFile.java [printStatistics]:1393) - dom.dbx DATA Buffers occupation : 100% (255 out of 256) Cache efficiency : 100% 
2018-02-20 16:21:06,834 [DefaultQuartzScheduler_Worker-1] INFO  (BTree.java [printStatistics]:2619) - collections.dbx INDEX Buffers occupation : 100% (1093 out of 1093) Cache efficiency : 100% 
2018-02-20 16:21:06,834 [DefaultQuartzScheduler_Worker-1] INFO  (BFile.java [printStatistics]:419) - collections.dbx DATA Buffers occupation : 99% (194 out of 195) Cache efficiency : 100% 
2018-02-20 16:21:06,834 [DefaultQuartzScheduler_Worker-1] INFO  (BTree.java [printStatistics]:2619) - values.dbx INDEX Buffers occupation : 2% (1 out of 64) Cache efficiency : 100% 
2018-02-20 16:21:06,834 [DefaultQuartzScheduler_Worker-1] INFO  (BFile.java [printStatistics]:419) - values.dbx DATA Buffers occupation : 0% (0 out of 64) Cache efficiency : N/A 
2018-02-20 16:46:37,470 [BrokerPools-ShutdownHook] INFO  (BrokerPools.java [run]:67) - Executing shutdown thread 
2018-02-20 16:46:37,470 [Thread-3] INFO  (JettyStart.java [lifeCycleStopping]:673) - Jetty server stopping... 
2018-02-20 16:46:37,471 [BrokerPools-ShutdownHook] INFO  (BrokerPool.java [shutdown]:1519) - Database is shutting down ... 
2018-02-20 16:46:37,516 [Thread-3] INFO  (AbstractConnector.java [doStop]:331) - Stopped ServerConnector@623dcf2a{HTTP/1.1,[http/1.1]}{0.0.0.0:8080} 
2018-02-20 16:46:37,518 [Thread-3] INFO  (AbstractConnector.java [doStop]:331) - Stopped ServerConnector@620c8641{SSL,[ssl, http/1.1]}{0.0.0.0:8443} 
2018-02-20 16:46:37,518 [Thread-3] INFO  (HouseKeeper.java [stopScavenging]:167) - Stopped scavenging 

2018-02-20 16:46:37,816 [BrokerPools-ShutdownHook] INFO  (BrokerPool.java [printSystemInfo]:1794) - SYSTEM INFO
Database instance: exist
-------------------------------------------------------------------
Threads currently waiting for a lock:
=====================================
Thread: qtp1004390006-1321
           Lock type: COLLECTION
           Lock mode: READ
             Lock id: /db/apps
             Held by: [qtp1004390006-1323]
             Held by: [qtp1004390006-1323]
             Held by: [qtp1004390006-1323]
    Waiting for read: []
   Waiting for write: []

```

### What did you expect
A functional database

### Describe how to reproduce or add a test
To be specified. Bulk upload data, access dashboard/exide....

### Context information
Please always add the following information
- eXist-db version : 4.0
- Java version (e.g. Java8u121) : Java8u151
- Operating system (Windows 7, Linux, MacOs) : windows7
- 32 or 64 bit : 64bit
- Any custom changes in e.g. conf.xml : none

**Comment by adamretter** [comment] 2018-02-20 16:33
Without a `jstack` or a mechanism to reproduce this, we won't be able to fix this.

**Comment by dizzzz** [comment] 2018-02-20 20:02
I'll try to re-reproduce

**Comment by duncdrum** [comment] 2019-01-12 10:45
could this be a duplicate of #1705 ?

**Comment by dizzzz** [comment] 2019-01-14 09:33
Possible yes. I'll try to reproduce.

**Closed** 2019-01-27 16:13 UTC
Labels: investigate
