### ISSUE TITLE
Reverting to old version of org.exist.Indexer.java produces invalid json

### ISSUE THREAD

**Issue by wshager** [eXist-db/exist#829] opened 2015-11-10 15:24 UTC
When using doc() to resolve a document, and then you serialize it to json, the hints below give invalid json:

``` xml
<root xmlns:json="http://www.json.org">
    <s>
        <json:value json:array="true">
            <a>A</a>
            <b>B</b>
        </json:value>
    </s>
</root>
```

**Comment by joewiz** [comment] 2015-11-10 17:12
Please post a full reproducible example, with actual results and expected results, would be great.

**Comment by wshager** [comment] 2015-11-10 22:12
You'd have to store this XML and call

```xquery
declare namespace output="http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method "json";
doc("doc.xml")
```

**Comment by dizzzz** [comment] 2015-11-10 22:15
Is storing the Xml required? Typically are tests without stored files easier to reproduce.

**Comment by wshager** [comment] 2015-11-10 22:18
Indeed, like I mentioned.

**Comment by wshager** [comment] 2015-11-10 22:19
The problem doesn't occur when the xml would be in the code.

**Comment by dizzzz** [comment] 2015-11-10 22:20
So when the Xml is in the query, it works ok?

**Comment by wshager** [comment] 2015-11-11 11:21
```xquery
xquery version "3.0";

declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
import module namespace json="http://www.json.org";

declare option output:method "json";
declare option output:media-type "application/json";

doc("/db/test/temp.xml")/root
```
produces `{ "s" : { [{ "a" : "A", "b" : "B" }] } }

```xquery
xquery version "3.0";

declare namespace output = "http://www.w3.org/2010/xslt-xquery-serialization";
import module namespace json="http://www.json.org";

declare option output:method "json";
declare option output:media-type "application/json";

<root xmlns:json="http://www.json.org">
    <s>
        <json:value json:array="true">
            <a>A</a>
            <b>B</b>
        </json:value>
    </s>
</root>```

produces `{ "s" : [{ "a" : "A", "b" : "B" }] }

**Comment by joewiz** [comment] 2015-11-11 20:27
I'm getting the second result for both in-memory in database versions of your query, using the latest nightly of the develop branch.

What version of eXist are you using?

**Comment by wshager** [comment] 2015-11-12 21:28
This one was tricky... I reverted back to an older version of org.exist.Indexer, because it gives white space errors when storing XML. This version apparently produces the wrong XML to serialize.

Please fix the org.exist.Indexer issue referenced in https://github.com/eXist-db/exist/pull/670

**Comment by joewiz** [comment] 2015-11-12 21:34
Sorry, @wshager, I'm unable to reproduce what you are reporting about this JSON issue.  Using your sample data and code, I am getting *only* valid JSON.  Unless you're able to provide more info to help reproduce your results, I suggest closing the issue.

**Comment by wshager** [comment] 2015-11-12 21:36
@joewiz really? Did you revert org.exist.Indexer **and save** the XML again?

**Comment by joewiz** [comment] 2015-11-12 21:39
No, I just used the latest develop branch. Are you saying your problem only happens when you revert org.exist.Indexer? And you did this to work around the bug reported in #670? If so, isn't this issue just a dupe of #670 and thus should be closed?

**Comment by wshager** [comment] 2015-11-12 21:42
I don't know, this seems relevant.

**Comment by joewiz** [comment] 2015-11-12 21:43
Okay, I leave it to you and others better versed in #670 to decide.

**Comment by joewiz** [comment] 2015-11-12 21:43
Sounds frustrating though!  Good luck!

**Comment by wshager** [comment] 2015-11-12 21:43
@joewiz thanks.

**Comment by joewiz** [comment] 2017-08-02 18:38
@wshager Is this still an issue with the current release? Is this still affecting you?

**Comment by duncdrum** [comment] 2019-01-08 13:39
closing due to lack of response. Please reopen if you still experience these problems.

**Closed by duncdrum** 2019-01-08 13:39 UTC
Labels: triage
