### ISSUE TITLE
Shortcuts points to the wrong port when eXist is running as a service

### ISSUE THREAD

**Issue by connietg** [eXist-db/exist#1621] opened 2017-11-20 06:58 UTC
eXist version: 3.5.0, downloaded from your web page 15th of November 2017
Java version: jre-8u152-windows-x64
Operating system: Windows 10, 64bit
Custom changes: changed ports from 8080 to 8082.

When eXist is running as a service, it redirects to localhost:8080 from the launcher when 'Open Dashboard', 'Open eXide' and 'Open Monitoring and Profiling' are clicked. When eXist do not run as a service, it redirect to localhost:8082 as it should do. It is not a huge bug, and easy enough to fix. But it should be unnessessary to change the URL of the web browser.

Connie.

![exist-launcher](https://user-images.githubusercontent.com/10898121/33005670-198173fa-cdc7-11e7-9767-87ee62108702.png)
Thank you for reporting your issue!

To be able to better understand you problem or suggestion, please add as much information as possible to this ticket. When there is no or just little information, it will be too difficult to work on it (and hence we will not be able to solve it)

Please fill in the following sections:

### What is the problem
> Describe exactly what you see (e.g. an output of an XQuery) 

### What did you expect
> Describe what you expected to happen. Add for example a reference to a [specification](https://www.w3.org/TR/xquery-3/).

### Describe how to reproduce or add a test
> Describe how we can can reproduce the problem.

> The *best* way is to provide a 'self containing' test, a test that can be run without dependancies. The [XQSuite - Annotation-based Test Framework for XQuery](http://exist-db.org/exist/apps/doc/xqsuite.xml) makes it very easy for you to create tests. These tests can be executed from the [eXide editor](http://exist-db.org/exist/apps/eXide/index.html) (XQuery - Run as Test)

### Context information
Please always add the following information
- eXist-db version + Git Revision hash e.g. eXist-db 3.0 /  acd0c14 
- Java version (e.g. Java8u121)
- Operating system (Windows 7, Linux, MacOs)
- 32 or 64 bit
- Any custom changes in e.g. conf.xml

**Comment by duncdrum** [comment] 2019-10-28 20:05
if anything this seems to be a duplicate of #1985. There have been substantial changes to how exist is running on WIN. If you still encounter this problem please open a new issue.

**Closed by duncdrum** 2019-10-28 20:05 UTC
Labels: YAJSW, investigate, windows
