### ISSUE TITLE
[BUG] NPE at org.exist.xquery.modules.range.RangeQueryRewriter.rewriteLocationStep

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#3624] opened 2020-11-20 22:26 UTC
**Describe the bug**

In eXist develop HEAD (5.3.0-SNAPSHOT), a new NPE is raised when running a query. The same query did not raise an NPE in the current stable release, 5.2.0.

**Expected behavior**

The query should not raise an NPE.

**To Reproduce**

To reproduce, install https://github.com/HistoryAtState/release (here's a prebuilt xar: [release-0.5.0.xar.zip](https://github.com/eXist-db/exist/files/5576302/release-0.5.0.xar.zip) - just remove the .zip extension), and open http://localhost:8080/exist/apps/release/ebook-batch.xq. The client sees the following 500 error:

> HTTP ERROR 500 javax.servlet.ServletException: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/release/ebook-batch.xq: An error occurred: null

Attached is the corresponding error from exist.log: [exist-log-npe-rangequeryrewriter.txt](https://github.com/eXist-db/exist/files/5576331/exist-log-npe-rangequeryrewriter.txt)

An excerpt:

```txt
2020-11-20 17:13:58,622 [qtp558431044-99] ERROR (EXistServlet.java [doGet]:291) - null 
java.lang.NullPointerException: null
	at org.exist.xquery.modules.range.RangeQueryRewriter.rewriteLocationStep(RangeQueryRewriter.java:109) ~[exist-index-range-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.exist.xquery.Optimizer.visitLocationStep(Optimizer.java:83) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.exist.xquery.LocationStep.accept(LocationStep.java:1242) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.exist.xquery.DynamicCardinalityCheck.accept(DynamicCardinalityCheck.java:139) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.exist.xquery.DefaultExpressionVisitor.visitBuiltinFunction(DefaultExpressionVisitor.java:48) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.exist.xquery.Function.accept(Function.java:526) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.exist.xquery.InternalFunctionCall.accept(InternalFunctionCall.java:271) ~[exist-core-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
```

Two clues: 

1. Performing the same steps from eXist 5.2.0 (stable) does not yield the error, but instead shows the expected HTML webpage. This suggests a regression in eXist 5.3.0-SNAPSHOT.

2. Also, commenting out https://github.com/HistoryAtState/release/blob/master/ebook-batch.xq#L198 allows eXist 5.3.0-SNAPSHOT to sidestep the error, so something in that code path must be triggering the NPE. I wasn't able to trace the source in my code, but I don't believe my code should be able to cause an NPE.

**Context (please always complete the following information):**
 - OS: macOS 11.0.1
 - eXist-db version: eXist 5.3.0-SNAPSHOT f65967548a9cc5886360cac80bc5cb1959d561be 20201119071106
 - Java Version: OpenJDK 1.8.0_275 (Liberica full)

**Additional context**
- How is eXist-db installed? built from source
- Any custom changes in e.g. `conf.xml`? none

**Comment by adamretter** [comment] 2020-11-23 10:12
That's very interesting! So this happens when trying to rewrite the query to replace a Location Step with a function which performs a Range Index comparison.

So the only way you could have `null` there is if the *Inner Expression* is not either:
1. A General Comparison, e.g. = !=, >=, eq, ne, ge, etc...
2. The functions `matches`.

The code is problematic, as it returns null in those cases, but then the code calling it does not expect/handle null and so you get an NPE.

As you describe not seeing this issue before, this however is possibly not the root cause. We would need to know what expression is causing the NPE to determine the root cause.

The first step would probably be to add some trace level logging into `Optimizer#visitLocationStep(LocationStep)` so that we can see what it is attempting to optimize.

**Comment by joewiz** [comment] 2020-12-04 05:45
@adamretter Thanks for your analysis and suggestion about how to proceed with determining the root cause. I'll let you know what we find.

**Comment by dizzzz** [comment] 2021-01-03 19:31
So my PR is not ok @adamretter @wolfgangmm ? shall I withdraw it ? :-(

**Comment by marmoure** [comment] 2023-03-06 14:05
i tried to reproduce  this issue in exist `6.2.0` c8fa4958b6d4a50bd0cba7f3e76a150226414187
i m not seeing any NPE or 500 error
i ll try again with other versions of exist

@joewiz  if can't reproduce the issue in the other versions as well
should i try to figure out why was it failing or can we mark it as done?

**Comment by marmoure** [comment] 2023-03-06 14:17
i tried to reproduce the issue against the develop branch commit: ad4bf8efc3b58bdd00431761dd796a5ae7913a75

and i got 
```xml
<exception>
    <path>/db/apps/release/ebook-batch.xq</path>
    <message>
           err:XPST0081 error found while loading module epub: Error while loading module modules/epub.xql: Invalid qname hc:send-request. No namespace defined for prefix hc. QName is invalid: INVALID_PREFIX [at line 104, column 30] 
    </message>
</exception>
```
 i m assuming this has nothing to do with original problem since i got it working on version `6.2.0`
 @joewiz please take a look

**Comment by adamretter** [comment] 2023-03-06 17:40
> I have tried to reproduce this issue in eXist-db 6.2.0, however I am not seeing any NPE.

So the PR (https://github.com/eXist-db/exist/pull/3625) that @dizzzz sent and was merged (see the history above) will stop that NPE from happening.

My feeling is that whilst the NPE no longer stops processing, there may be another underlying bug. If you were to take a version of eXist-db 6.2.0, and comment out the NPE protection (that @dizzzz added in https://github.com/eXist-db/exist/pull/3625), then you may be able to reproduce the issue that Joe reported. Ideally being able to reproduce that would show us the underlying bug, and we could discuss how to address that.

> I am assuming this has nothing to do with original problem since I got it working on version `6.2.0`.

@marmoure You are correct, that error you are seeing appears to be because `ebook-batch.xq` has not yet been updated to work with eXist-db 7.x.x.

**Comment by marmoure** [comment] 2023-03-14 14:35
after removing #3625 and getting the NPE back 
This looked like a regression bug, so I started comparing Exist-6.2.0 c8fa4958b6d4a50bd0cba7f3e76a150226414187 against Exist-5.2.0 c58d04ec45de50e7738489dee072fcc863dc8b1b
and try to find where the code branch occurs.
i found out that exist-5.2.0 was not using any Range index while exist-6.2.0  was trying to do so.
The difference was due to the query being transformed  and a `range:eq` was introduced in place of an equal statement.
and it looks like this
`attribute::{}rend = "sectiontitlebold" `
compared to
`range:eq(attribute::{}rend, "sectiontitlebold")`
This replacement was done by the optimizer during the query `analysis` phase.
So far  we think it's due to an error in handling the query.
You can see the difference in that specific query by setting a breakpoint in both versions in this line.
https://github.com/eXist-db/exist/blob/c8fa4958b6d4a50bd0cba7f3e76a150226414187/exist-core/src/main/java/org/exist/xquery/Optimizer.java#L81
with this specific condition: `locationStep.toString().equals("self::tei:p[attribute::{}rend = \"sectiontitlebold\"]")`
You'll see:
```
not(self::tei:p[attribute::{}rend = "sectiontitlebold"]) => exist_6.2.0
self::tei:p[attribute::{}rend = "sectiontitlebold"] => exist_5.x.x
```

So far, this means we have a bug that has been introduced in the optimizer.
and also when we checked the optimizer function 
https://github.com/eXist-db/exist/blob/c8fa4958b6d4a50bd0cba7f3e76a150226414187/extensions/indexes/range/src/main/java/org/exist/xquery/modules/range/RangeQueryRewriter.java#L44

There are no checks in place to make sure there is a range index defined when trying to optimize.
So this is a second potential bug.

**Closed** 2024-09-02 15:02 UTC
Labels: bug
