### ISSUE TITLE
Recent versions of XSLTForms fail to run in eXist 3.0.RC1 

### ISSUE THREAD

**Issue by timathom** [eXist-db/exist#838] opened 2015-11-22 22:29 UTC
XSLTForms is now on rev. 627, but any version later than rev. 594 is currently failing in eXist 3.0.RC1. This was first reported on the XSLTForms support list (http://sourceforge.net/p/xsltforms/mailman/message/34278223/) in July. Subsequent follow up with Alain Couthures and @wolfgangmm pointed to #670 as a potential source of the problem. 

According to Alain: 

> New XSLTForms builds define an XSLT variable to be used in XPath expression:
> 
> ```
>         <xsl:variable xmlns:xsl="http://www.w3.org/1999/XSL/Transform" name="newline"><xsl:text>
> </xsl:text></xsl:variable>`
> ```
> 
> This has to be preserved because the XSLTForms XPath parser is written with XSLT named templates.

**Comment by duncdrum** [comment] 2019-01-08 13:42
duplicate of #1072

**Closed by duncdrum** 2019-01-08 13:42 UTC
Labels: triage
