### ISSUE TITLE
[BUG] type checking on `for` variable binding 

### ISSUE THREAD

**Issue by PieterLamers** [eXist-db/exist#3971] opened 2021-07-06 19:15 UTC
**Describe the bug**
Type checking on the variable binding of a `for` statement returns errors which I think show that the return value of the FLOWR is evaluated instead of the `for` binding (https://www.w3.org/TR/xquery-31/#prod-xquery31-ForBinding).

**Expected behavior**
I expect the type declaration to match the value of `$string` in the example below.

**To Reproduce**
```xquery
let $my-sequence as xs:string+ := ('my','sequence')
for $string as xs:string in $my-sequence
return <foo/>
```
The above returns the error `err:XPTY0004 Invalid type for variable $string. Expected xs:string, got element()` where it should simply return `<foo/>,<foo/>`. @joewiz confirmed that BaseX and Saxon return the latter.

**Context (please always complete the following information):**
 - OS: Windows, Linux
 - eXist-db version: 5.3.0, 4.7
 - Java Version 1.8.0_282

**Comment by line-o** [comment] 2021-07-06 19:21
@PieterLamers this looks like a duplicate of #3553

**Comment by joewiz** [comment] 2021-07-06 19:24
Agreed, it's a dupe. I'll add an xqsuite test to 3553.

**Closed by joewiz** 2021-07-06 19:24 UTC
Labels: awaiting-response
