### ISSUE TITLE
yajsw wrapper does not work on Ubuntu

### ISSUE THREAD

**Issue by tasmo** [eXist-db/exist#1154] opened 2016-10-26 12:57 UTC
When I tried to start exist with yajsw I got a bunch of errors and exist does not run although the wrapper script seems to start.

The directory `/tmp/vfs_cache` is needed by the wrapper. So I solved the Java error by creating it.

The errors caused by the missing libs in `tools/yajsw/lib/extended/` are not important but I installed the missing libs from the yajsw sources.

The next problem is (and still is) the `${env.EXIST_HOME}` environment variable. The system itself echoes the right path with `echo $EXIST_HOME` in any shell. Since I changed that with success the wrapper now does not try to make the folder with the name `${env.EXIST_HOME}` anymore but one with the name `?unresolved?` in the root of `$EXIST_HOME`.

exist is still not running after a successful installation with `./tools/yajsw/bin/installDaemon.sh`; `sudo systemctl daemon-reload` and `sudo systemctl start eXist-db`. systemctl starts the script and echoes success. Nor a direct call with `/etc/init.d/eXist-db start` leaves a running exist.

Starting `bin/startup.sh` in a screen session runs exist without any errors.

**Comment by dizzzz** [comment] 2016-10-26 19:23
duplicate of https://github.com/eXist-db/exist/issues/1147

**Comment by dizzzz** [comment] 2016-10-26 21:09
thnx for your useful details....

**Comment by tasmo** [comment] 2016-10-27 08:59
Thought because the issue #1147 is about macOS. :)

**Comment by dizzzz** [comment] 2016-10-27 09:12
Right you are, But it is the same issue :)

**Comment by dizzzz** [comment] 2016-11-04 14:33
issue is still valid, and different that macOS

**Comment by joewiz** [comment] 2016-12-21 16:23
Is this issue still present now that #1165 has been merged?

**Comment by adamretter** [comment] 2016-12-22 16:37
@tasmo Is this now fixed for you with HEAD?

**Comment by duncdrum** [comment] 2019-10-28 20:01
YAJSW is gone, no response since 2016. Closing

**Closed by duncdrum** 2019-10-28 20:01 UTC
Labels: YAJSW, bug
