### ISSUE TITLE
How can I convert Document to NodeValue

### ISSUE THREAD

**Issue by meshkin** [eXist-db/exist#802] opened 2015-09-30 13:05 UTC
hi all,
I am Writing a custom extension plugin, but I received the below error:
error: org.apache.xerces.dom.DocumentImpl cannot be cast to org.exist.xquery.value.NodeValue
how can I convert "org.w3c.dom.Document" object to NodeValue or a Document in eXist?
Thanks

**Comment by joewiz** [comment] 2015-09-30 19:38
Please ask questions on the exist-open mailing list. The eXist community reserves issues for bugs that've been confirmed on the mailing list; it's not the place for general questions. For more on this, see the project readme, which links to http://www.exist-db.org/exist/apps/doc/getting-help.xml.

**Comment by dizzzz** [comment] 2015-10-01 11:48
And..... if you post your question, please post a code fragment so we do not have to guess :-)

**Comment by jensopetersen** [comment] 2015-10-01 13:17
I would say that you should add "/*" to your expression …. You are getting a document node and you probably want a document element.

Just guessing …

**Comment by wolfgangmm** [comment] 2015-10-01 13:29
You need to convert your org.w3c.dom.Document into eXist's own in-memory DOM, so the query engine can process it further. There are several ways to do this, depending on where the data is coming from (SAX stream, XML parser)?

**Comment by duncdrum** [comment] 2018-10-01 17:37
Closing, because ancient. If you still have questions please open another issue.

**Closed by duncdrum** 2018-10-01 17:37 UTC
Labels: question
