### ISSUE TITLE
Running build.sh with no conf.xml changes makes the Dashboard Crash

### ISSUE THREAD

**Issue by agucabral21** [eXist-db/exist#2052] opened 2018-07-20 16:54 UTC
I was trying to add the Cache Module to eXist-db 4.2.1, but when I run `./build.sh extension-modules` and start eXist-db again, the web dashboard crashes, and logs the following error (tried to sum up the log):

```
2018-07-20 13:07:00,440 [qtp665512315-37] WARN  (HttpChannel.java [handleException]:573) - /exist/apps/bfResources/scripts/dojox/form/resources/UploaderFileList.css
javax.servlet.ServletException: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/bfResources/scripts/dojox/form/resources/UploaderFileList.css: Failed to initialize request dispatcher to forward request to /apps/bfResources/scripts/dojox/form/resources/UploaderFileList.css
Caused by: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/bfResources/scripts/dojox/form/resources/UploaderFileList.css: Failed to initialize request dispatcher to forward request to /apps/bfResources/scripts/dojox/form/resources/UploaderFileList.css
Caused by: javax.servlet.ServletException: Failed to initialize request dispatcher to forward request to /apps/bfResources/scripts/dojox/form/resources/UploaderFileList.css
2018-07-20 13:07:00,442 [qtp665512315-22] WARN  (HttpChannel.java [handleException]:573) - /exist/apps/bfResources/scripts/dojo/dojo.js
javax.servlet.ServletException: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/bfResources/scripts/dojo/dojo.js: Failed to initialize request dispatcher to forward request to /apps/bfResources/scripts/dojo/dojo.js
Caused by: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/bfResources/scripts/dojo/dojo.js: Failed to initialize request dispatcher to forward request to /apps/bfResources/scripts/dojo/dojo.js
Caused by: javax.servlet.ServletException: Failed to initialize request dispatcher to forward request to /apps/bfResources/scripts/dojo/dojo.js
2018-07-20 13:07:00,443 [qtp665512315-25] WARN  (HttpChannel.java [handleException]:573) - /exist/apps/bfResources/scripts/dojox/grid/resources/nihiloGrid.css
javax.servlet.ServletException: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/bfResources/scripts/dojox/grid/resources/nihiloGrid.css: Failed to initialize request dispatcher to forward request to /apps/bfResources/scripts/dojox/grid/resources/nihiloGrid.css
Caused by: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/bfResources/scripts/dojox/grid/resources/nihiloGrid.css: Failed to initialize request dispatcher to forward request to /apps/bfResources/scripts/dojox/grid/resources/nihiloGrid.css
Caused by: javax.servlet.ServletException: Failed to initialize request dispatcher to forward request to /apps/bfResources/scripts/dojox/grid/resources/nihiloGrid.css
2018-07-20 13:07:00,445 [qtp665512315-24] WARN  (HttpChannel.java [handleException]:573) - /exist/apps/bfResources/scripts/dijit/themes/nihilo/nihilo.css
javax.servlet.ServletException: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/bfResources/scripts/dijit/themes/nihilo/nihilo.css: Failed to initialize request dispatcher to forward request to /apps/bfResources/scripts/dijit/themes/nihilo/nihilo.css
Caused by: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/bfResources/scripts/dijit/themes/nihilo/nihilo.css: Failed to initialize request dispatcher to forward request to /apps/bfResources/scripts/dijit/themes/nihilo/nihilo.css
Caused by: javax.servlet.ServletException: Failed to initialize request dispatcher to forward request to /apps/bfResources/scripts/dijit/themes/nihilo/nihilo.css
javax.servlet.ServletException: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/bfResources/scripts/dojo/dojo.js: Failed to initialize request dispatcher to forward request to /apps/bfResources/scripts/dojo/dojo.js
Caused by: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/bfResources/scripts/dojo/dojo.js: Failed to initialize request dispatcher to forward request to /apps/bfResources/scripts/dojo/dojo.js
Caused by: javax.servlet.ServletException: Failed to initialize request dispatcher to forward request to /apps/bfResources/scripts/dojo/dojo.js
```

So I installed eXist-db again and ran `./build.sh extension-modules` without adding the Cache Module in `conf.xml`,  I just ran the script without changing anything, and I got the same result, i.e. the Dashboard crashes.

## Context info

-  Running with Java 1.8.0_171 [Oracle Corporation (Java HotSpot(TM) 64-Bit Server VM) in /opt/apps/java/jdk1.8.0_171/jre

- eXist Version : 4.2.1

-  3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u2 (2017-06-26) x86_64 GNU/Linux

**Comment by agucabral21** [comment] 2018-07-20 18:33
well.. ive tried it with 4.3.0, and it works without adding the cache-module, now im trying that.

**Comment by adamretter** [comment] 2018-07-23 05:34
@agucabral21 Can you tell me how you installed eXist-db please? Did you use the Jar installer, the DMG for Mac, or some other process?

**Comment by agucabral21** [comment] 2018-07-30 14:29
@adamretter sorry for the delay, i installed it using the jar instaler and by console
the information was in the exist.log file indeed
urlrewrite.log has the same log errors exist.log has

**Comment by adamretter** [comment] 2018-07-30 17:31
Okay I can reproduce the problem.

The issue is that the betterForm resources servlet is not included in `webapp/WEB-INF/web.xml`.

Instead of `build.sh extension-modules` can you please try `build.sh extension-betterform extension-modules`?

**Comment by agucabral21** [comment] 2018-08-15 20:16
Still have errors when trying the dashboard

[exist.log](https://github.com/eXist-db/exist/files/2291544/exist.log)
[urlrewrite.log](https://github.com/eXist-db/exist/files/2291545/urlrewrite.log)

**Comment by adamretter** [comment] 2018-08-16 05:28
@agucabral21 looks like the same problem. Did you try my advice above? If that still doesn't work, can you try a fresh checkout/install and then my advice above?

**Comment by agucabral21** [comment] 2018-08-23 17:32
adam, that is what i do, i reinstall existdb from start, then run build.sh extension-betterform extension-modules and i keep getting the same error, i will try this again tomorrow, sorry for the delay between responses, i will be faster to get you back from now on!

**Comment by agucabral21** [comment] 2018-09-05 17:11
@adamretter still getting the same problem, this time i tried with exist version 4.3.1

Insalled Exist from start
Start exist to check if everything is ok
Shutdown exist
Moved webapp/WEB-INF/web.xml
Run `build.sh extension-betterform extension-modules`

And i keep getting the same problem, dashboard wont start and logs same errors.

[urlrewrite.log](https://github.com/eXist-db/exist/files/2353830/urlrewrite.log)
[exist.log](https://github.com/eXist-db/exist/files/2353831/exist.log)


Context: 

Running with Java 1.8.0_171 [Oracle Corporation (Java HotSpot(TM) 64-Bit Server VM) in /opt/apps/java/jdk1.8.0_171/jre

eXist Version : 4.3.1

3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u2 (2017-06-26) x86_64 GNU/Linux

**Comment by agucabral21** [comment] 2018-09-24 17:30
@adamretter , i've found another problem but already solved it, im using external jars in my installation, and in this latest version the eXist-settings.sh file, doesnt have the `-Djava.endorsed.dirs=${JAVA_ENDORSED_DIRS}` property in the set_java_options() function

I was using exist 2.2 and trying to migrate to  4.3.1 and these are the differences

On exist 2.2
`set_java_options() {
    if [ -z "${JAVA_OPTIONS}" ]; then
	JAVA_OPTIONS="-Xss32m -Xms128m -Xmx4096m -Dfile.encoding=UTF-8";
    fi
    JAVA_OPTIONS="${JAVA_OPTIONS} -Djava.endorsed.dirs=${JAVA_ENDORSED_DIRS}";
}`

on exist 4.3.1
`set_java_options() {
    if [ -z "${JAVA_OPTIONS}" ]; then
	JAVA_OPTIONS="-Xms128m -Xmx4096m -Dfile.encoding=UTF-8";
    fi
    JAVA_OPTIONS="${JAVA_OPTIONS}";
}`

so i just added it, this way i can add to the startup.sh my jar folders like this
(code in startup,sh)
```
JAVA_ENDORSED_DIRS="$EXIST_HOME"/lib/endorsed:"$EXIST_HOME"/lib/mdm
export JAVA_ENDORSED_DIRS
set_java_options;

```

**Comment by dizzzz** [comment] 2018-09-24 18:14
JAVA_ENDORSED_DIRS is not supported anymore starting java8 or so.

**Comment by adamretter** [comment] 2018-09-25 04:45
@agucabral21 Glad you resolved your build issue.

As @dizzzz mentioned Java 9 onwards does not have an "endorsed" mechanism. You can place custom jars into `$EXIST_HOME/lib/user`. 

Can we close this issue now?

**Comment by agucabral21** [comment] 2018-09-25 13:28
Ok! im using java 8 now but ill keep that in mind...
yeap close it!
Thank you!

**Closed** 2018-09-25 13:45 UTC
Labels: question
