### ISSUE TITLE
Path expression with nested positional predicate fails on database node

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist#1892] opened 2018-05-30 04:15 UTC
### What is the problem

A path expression containing a nested positional predicate, which works on an in-memory node, fails on an identical node stored in the database.

### What did you expect

I expected a path expression on a structure to work uniformly whether it is in-memory or stored in the database.

### Describe how to reproduce or add a test

The following xqsuite test, adapted from @ChristianGruen's https://github.com/BaseXdb/basex/issues/1573, shows how the in-database function fails while the in-memory function works correctly.

```xquery
xquery version "3.1";

module namespace npt="http://exist-db.org/test/nested-positional-predicate";

declare namespace test="http://exist-db.org/xquery/xqsuite";

declare variable $npt:DATA :=
    document {
        <xml>
            <a>
                <b>A</b>
            </a>
            <a>
                <b>B</b>
                <c>correct</c>
            </a>
            <a>
                <b>B</b>
                <c>wrong</c>
            </a>
        </xml>
    };
    
declare
    %test:setUp
function npt:setup() {
    xmldb:create-collection("/db", "test"),
    xmldb:store("/db/test", "test.xml", $npt:DATA)
};

declare
    %test:tearDown
function npt:cleanup() {
    xmldb:remove("/db/test")
};

declare
    %test:assertEquals("<c>correct</c>")
function npt:in-memory() {
    $npt:DATA//c[../preceding-sibling::a[1]/b = 'A']
};

declare
    %test:assertEquals("<c>correct</c>")
function npt:in-database() {
    doc("/db/test.xml")//c[../preceding-sibling::a[1]/b = 'A']
};
```

The results:

```xml
<testsuites>
    <testsuite package="http://exist-db.org/test/nested-positional-predicate"
        timestamp="2018-05-29T23:01:23.898-05:00" failures="1" pending="0" tests="2" time="PT0.029S">
        <testcase name="in-database" class="npt:in-database">
            <failure
                message="assertEquals failed: wrong number of items returned by function. Expected: 1. Got: 0"
                type="failure-error-code-1">&lt;c&gt;correct&lt;/c&gt;</failure>
            <output/>
        </testcase>
        <testcase name="in-memory" class="npt:in-memory"/>
    </testsuite>
</testsuites>
```

### Context information

- eXist-db version + Git Revision hash: eXist-db 4.2.0-SNAPSHOT+201805281153 (e46c45c9d) 
- Java version: Oracle JDK 1.8.0_172-b11
- Operating system: macOS 10.13.4
- 32 or 64 bit: 64 bit
- Any custom changes in e.g. conf.xml: none

**Comment by duncdrum** [comment] 2018-05-30 08:36
@joewiz just for reference in case we do use saxon under the hood here: https://saxonica.plan.io/issues/3758
https://saxonica.plan.io/issues/3666

**Comment by adamretter** [comment] 2018-08-12 07:03
I think I might have fixed this here: https://github.com/adamretter/exist/commit/00ec2d7e48e5cb517349bc7ca69e56144f70d6d5 there will be a Pull Request soon I hope.

**Comment by adamretter** [comment] 2018-08-13 13:27
@joewiz Okay my PR which might help with this is here - https://github.com/eXist-db/exist/issues/1691 please can you test?

**Comment by joewiz** [comment] 2018-08-13 13:37
@adamretter The error still appears to be present. Checking out #2113 and running the xqsuite test above, the result is:

```xml
<testsuites>
    <testsuite package="http://exist-db.org/test/nested-positional-predicate"
        timestamp="2018-08-13T09:35:08.599-04:00" tests="2" failures="1" errors="0" pending="0"
        time="PT0.025S">
        <testcase name="in-database" class="npt:in-database">
            <failure
                message="assertEquals failed: wrong number of items returned by function. Expected: 1. Got: 0"
                type="failure-error-code-1">&lt;c&gt;correct&lt;/c&gt;</failure>
            <output/>
        </testcase>
        <testcase name="in-memory" class="npt:in-memory"/>
    </testsuite>
</testsuites>
```

**Comment by adamretter** [comment] 2018-08-14 13:32
I was able to reduce your test case further to this:

```xquery
declare
    %test:assertEquals("<c>correct</c><c>wrong</c>")
function npt:in-database-predicate() {
    doc("/db/test.xml")//c[../preceding-sibling::a[1]]
};
```
Interestingly, if I use `position()` in the predicate instead of just a numeric position then the test passes, e.g.

```xquery
declare
    %test:assertEquals("<c>correct</c><c>wrong</c>")
function npt:in-database-position() {
    doc("/db/test.xml")//c[../preceding-sibling::a[position() eq 1]]
};
```

**Comment by adamretter** [comment] 2018-08-14 15:33
I am really struggling to find where the problem is here, I think it is somehow related to predicate evaluation, perhaps @wolfgangmm has some thoughts?

**Comment by adamretter** [comment] 2018-08-14 15:34
I have these test cases now:

```xquery
xquery version "3.1";

module namespace npt="http://exist-db.org/test/nested-positional-predicate";

declare namespace test="http://exist-db.org/xquery/xqsuite";

declare variable $npt:DATA :=
    document {
        <xml>
            <a>
                <b>B1</b>
            </a>
            <a>
                <b>B2</b>
                <c>correct</c>
            </a>
            <a>
                <b>B3</b>
                <c>wrong</c>
            </a>
        </xml>
    };

declare
    %test:setUp
function npt:setup() {
    xmldb:create-collection("/db", "test"),
    xmldb:store("/db/test", "test.xml", $npt:DATA)
};

declare
    %test:tearDown
function npt:cleanup() {
    xmldb:remove("/db/test")
};

declare
    %test:assertEquals("<c>correct</c><c>wrong</c>")
function npt:in-memory() {
    $npt:DATA//c[../preceding-sibling::a]
};

declare
    %test:assertEquals("<c>correct</c><c>wrong</c>")
function npt:in-database() {
    doc("/db/test.xml")//c[../preceding-sibling::a]
};


declare
    %test:assertEquals("<c>correct</c><c>wrong</c>")
function npt:in-memory-predicate() {
    $npt:DATA//c[../preceding-sibling::a[1]]
};

declare
    %test:assertEquals("<c>correct</c><c>wrong</c>")
function npt:in-database-predicate() {
    doc("/db/test.xml")//c[../preceding-sibling::a[1]]
};

declare
    %test:assertEquals("<c>correct</c><c>wrong</c>")
function npt:in-memory-position() {
    $npt:DATA//c[../preceding-sibling::a[position() eq 1]]
};

declare
    %test:assertEquals("<c>correct</c><c>wrong</c>")
function npt:in-database-position() {
    doc("/db/test.xml")//c[../preceding-sibling::a[position() eq 1]]
};

declare
    %test:assertEquals("<c>correct</c>")
function npt:in-memory-predicate-and-path() {
    $npt:DATA//c[../preceding-sibling::a[1]/b = 'B1']
};

declare
    %test:assertEquals("<c>correct</c>")
function npt:in-database-predicate-and-path() {
    doc("/db/test.xml")//c[../preceding-sibling::a[1]/b = 'B1']
};

declare
    %test:assertEquals("<c>correct</c>")
function npt:in-memory-position-and-path() {
    $npt:DATA//c[../preceding-sibling::a[position() eq 1]/b = 'B1']
};

declare
    %test:assertEquals("<c>correct</c>")
function npt:in-database-position-and-path() {
    doc("/db/test.xml")//c[../preceding-sibling::a[position() eq 1]/b = 'B1']
};
```

**Comment by merenyics** [comment] 2019-05-22 18:15
also note that:
`$coll//a[1]` is fast, but `$coll//b/a[1]` is VERY slow (talking about db nodes here, not sure about in-memory).
`a[position()=1]` always seems to perform acceptably. While this is a feasible workaround, positional predicates seem to need more attention in general.

**Comment by joewiz** [comment] 2019-09-10 14:13
Both my original tests and @adamretter's modified tests all still fail in eXist 5.0.0.

**Comment by ccheraa** [comment] 2022-07-06 05:07
I have changed `doc("/db/test.xml")` to `doc("/db/test/test.xml")` as I think it was only a typo, so the function is:
```xquery
declare
    %test:assertEquals("<c>correct</c>")
function npt:in-database() {
    doc("/db/test/test.xml")//c[../preceding-sibling::a[1]/b = 'A']
};
```

And have tested it on `6.1.0-SNAPSHOT`, `6.0.1`, `5.2.0`, and `4.10.0`, and none of them had this issue anymore.
The test results for them were:

```xml
<testsuites>
    <testsuite package="http://exist-db.org/test/nested-positional-predicate" timestamp="2022-07-06T05:03:36.34Z" tests="2" failures="0" errors="0" pending="0" time="PT0.017S">
        <testcase name="in-database" class="npt:in-database"/>
        <testcase name="in-memory" class="npt:in-memory"/>
    </testsuite>
</testsuites>
```

**Comment by adamretter** [comment] 2022-07-06 16:06
@joewiz I think also it is likely there was an issue which was fixed in the interim also.

**Closed** 2022-07-16 17:21 UTC
Labels: bug
